// <auto-generated>
// Engine-owned party-RPG toolkit. Projects provide content and presentation;
// these types provide deterministic rules, snapshots, and composition points.
// </auto-generated>
#nullable enable
using System.Text.Json;
using System.Text.Json.Serialization;
using Engine.Gameplay;

namespace Engine.Jrpg;

public static class JrpgJson
{
    public static readonly JsonSerializerOptions Options = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower,
        WriteIndented = false,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }
    };
}

public sealed record StatBlock(
    int MaxHp = 1,
    int MaxMp = 0,
    int Attack = 0,
    int Defense = 0,
    int Magic = 0,
    int Resistance = 0,
    int Speed = 0,
    int Luck = 0)
{
    public StatBlock Clamp() => new(
        Math.Max(1, MaxHp),
        Math.Max(0, MaxMp),
        Math.Max(0, Attack),
        Math.Max(0, Defense),
        Math.Max(0, Magic),
        Math.Max(0, Resistance),
        Math.Max(0, Speed),
        Math.Max(0, Luck));

    public StatBlock Add(StatBlock other) => new StatBlock(
        SaturatingAdd(MaxHp, other.MaxHp),
        SaturatingAdd(MaxMp, other.MaxMp),
        SaturatingAdd(Attack, other.Attack),
        SaturatingAdd(Defense, other.Defense),
        SaturatingAdd(Magic, other.Magic),
        SaturatingAdd(Resistance, other.Resistance),
        SaturatingAdd(Speed, other.Speed),
        SaturatingAdd(Luck, other.Luck)).Clamp();

    private static int SaturatingAdd(int left, int right) =>
        (int)Math.Clamp((long)left + right, int.MinValue, int.MaxValue);
}

public sealed record StatModifier(string Source, StatBlock Flat);

public interface IExperienceCurve
{
    ulong TotalExperienceForLevel(ushort level);
}

public sealed class QuadraticExperienceCurve : IExperienceCurve
{
    public ulong Base { get; init; } = 100;
    public ulong Growth { get; init; } = 25;

    public ulong TotalExperienceForLevel(ushort level)
    {
        var completed = (ulong)Math.Max(0, level - 1);
        var prior = completed == 0 ? 0 : completed - 1;
        return checked(Base * completed + Growth * completed * prior / 2);
    }
}

public sealed record LevelGain(ushort OldLevel, ushort NewLevel, ulong Experience);

public sealed class CharacterProgress
{
    public required string ActorId { get; init; }
    public required string DisplayNameKey { get; init; }
    public ushort Level { get; set; } = 1;
    public ulong Experience { get; set; }
    public uint SkillPoints { get; set; }
    public StatBlock BaseStats { get; init; } = new();
    public HashSet<string> LearnedAbilities { get; init; } = new(StringComparer.Ordinal);
    public Dictionary<string, string> Equipment { get; init; } = new(StringComparer.Ordinal);

    public LevelGain GrantExperience(
        ulong amount,
        ushort levelCap = 99,
        IExperienceCurve? curve = null)
    {
        curve ??= new QuadraticExperienceCurve();
        var old = Level;
        Experience = SaturatingAdd(Experience, amount);
        while (Level < levelCap && Experience >= curve.TotalExperienceForLevel((ushort)(Level + 1)))
        {
            Level++;
            SkillPoints++;
        }
        return new LevelGain(old, Level, amount);
    }

    public StatBlock ResolveStats(IEnumerable<StatModifier> modifiers)
    {
        var result = BaseStats.Clamp();
        foreach (var modifier in modifiers)
            result = result.Add(modifier.Flat);
        return result;
    }

    private static ulong SaturatingAdd(ulong left, ulong right) =>
        ulong.MaxValue - left < right ? ulong.MaxValue : left + right;
}

public enum ItemKind { Consumable, Equipment, Material, KeyItem }

public sealed class EquipmentDefinition
{
    public required string Slot { get; init; }
    public List<StatModifier> Modifiers { get; init; } = new();
    public List<string> GrantedAbilities { get; init; } = new();
}

public sealed class ItemDefinition
{
    public required string Id { get; init; }
    public required string DisplayNameKey { get; init; }
    public ItemKind Kind { get; init; }
    public uint StackLimit { get; init; } = 99;
    public string? ConsumableAbility { get; init; }
    public EquipmentDefinition? Equipment { get; init; }

    public void Validate()
    {
        if (string.IsNullOrWhiteSpace(Id) || StackLimit == 0)
            throw new InvalidOperationException("Item id and stack limit must be valid.");
        if (Kind == ItemKind.Equipment && Equipment == null)
            throw new InvalidOperationException($"Equipment item '{Id}' has no descriptor.");
    }
}

public sealed class Inventory
{
    public int DistinctCapacity { get; init; } = 256;
    public Dictionary<string, uint> Stacks { get; init; } = new(StringComparer.Ordinal);

    public uint Quantity(string itemId) => Stacks.GetValueOrDefault(itemId);

    public uint Add(ItemDefinition item, uint quantity)
    {
        item.Validate();
        if (quantity == 0) return Quantity(item.Id);
        if (!Stacks.ContainsKey(item.Id) && Stacks.Count >= DistinctCapacity)
            throw new InvalidOperationException("Inventory distinct-item capacity reached.");
        var next = checked(Quantity(item.Id) + quantity);
        if (next > item.StackLimit)
            throw new InvalidOperationException($"Item '{item.Id}' stack exceeds {item.StackLimit}.");
        Stacks[item.Id] = next;
        return next;
    }

    public uint Remove(string itemId, uint quantity)
    {
        var current = Quantity(itemId);
        if (quantity > current)
            throw new InvalidOperationException($"Not enough '{itemId}'.");
        var remaining = current - quantity;
        if (remaining == 0) Stacks.Remove(itemId);
        else Stacks[itemId] = remaining;
        return remaining;
    }

    public string? Equip(
        CharacterProgress actor,
        ItemDefinition item,
        IReadOnlyDictionary<string, ItemDefinition> definitions)
    {
        var equipment = item.Equipment ??
            throw new InvalidOperationException($"Item '{item.Id}' is not equipment.");
        if (Quantity(item.Id) == 0)
            throw new InvalidOperationException($"Not enough '{item.Id}'.");
        actor.Equipment.TryGetValue(equipment.Slot, out var previous);
        ItemDefinition? previousDefinition = null;
        if (previous != null)
        {
            if (!definitions.TryGetValue(previous, out previousDefinition))
                throw new InvalidOperationException($"Unknown equipped item '{previous}'.");
            if (Quantity(previous) >= previousDefinition.StackLimit)
                throw new InvalidOperationException($"Cannot return '{previous}' to a full stack.");
        }
        Remove(item.Id, 1);
        actor.Equipment[equipment.Slot] = item.Id;
        if (previousDefinition != null) Add(previousDefinition, 1);
        return previous;
    }
}

public sealed class Party
{
    public int ActiveLimit { get; init; } = 4;
    public ulong Currency { get; set; }
    public Dictionary<string, CharacterProgress> Actors { get; init; } = new(StringComparer.Ordinal);
    public List<string> Active { get; init; } = new();
    public List<string> Reserve { get; init; } = new();

    public void Recruit(CharacterProgress actor, bool preferActive = true)
    {
        if (!Actors.TryAdd(actor.ActorId, actor))
            throw new InvalidOperationException($"Actor '{actor.ActorId}' is already recruited.");
        if (preferActive && Active.Count < ActiveLimit) Active.Add(actor.ActorId);
        else Reserve.Add(actor.ActorId);
    }

    public void SetActive(IEnumerable<string> actorIds)
    {
        var requested = actorIds.ToList();
        if (requested.Count > ActiveLimit || requested.Distinct(StringComparer.Ordinal).Count() != requested.Count)
            throw new InvalidOperationException("Active party is too large or contains duplicates.");
        if (requested.Any(id => !Actors.ContainsKey(id)))
            throw new InvalidOperationException("Active party contains an unknown actor.");
        Active.Clear();
        Active.AddRange(requested);
        Reserve.Clear();
        Reserve.AddRange(Actors.Keys.Where(id => !Active.Contains(id, StringComparer.Ordinal)));
    }

    public void GrantCurrency(ulong amount) => Currency = checked(Currency + amount);

    public void SpendCurrency(ulong amount)
    {
        if (amount > Currency) throw new InvalidOperationException("Not enough currency.");
        Currency -= amount;
    }
}

public enum BattleSide { Party, Enemy }
public enum DamageKind { Physical, Magical, Direct }
public enum Element { Neutral, Fire, Ice, Lightning, Water, Wind, Earth, Light, Dark }
public enum TargetRule { SelfUnit, SingleAlly, AllAllies, SingleEnemy, AllEnemies, AnySingle }
public enum BattlePhase { Running, PartyVictory, EnemyVictory, Escaped }

[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
[JsonDerivedType(typeof(DamageEffect), "damage")]
[JsonDerivedType(typeof(HealEffect), "heal")]
[JsonDerivedType(typeof(RestoreMpEffect), "restore_mp")]
[JsonDerivedType(typeof(AddStatusEffect), "add_status")]
[JsonDerivedType(typeof(RemoveStatusEffect), "remove_status")]
[JsonDerivedType(typeof(ReviveEffect), "revive")]
public abstract record BattleEffect;
public sealed record DamageEffect(int Power, DamageKind Kind, Element Element = Element.Neutral) : BattleEffect;
public sealed record HealEffect(int Power) : BattleEffect;
public sealed record RestoreMpEffect(int Amount) : BattleEffect;
public sealed record AddStatusEffect(string StatusId, int ChanceBasisPoints = 10_000) : BattleEffect;
public sealed record RemoveStatusEffect(string StatusId) : BattleEffect;
public sealed record ReviveEffect(int HealthBasisPoints) : BattleEffect;

public sealed class AbilityDefinition
{
    public required string Id { get; init; }
    public required string DisplayNameKey { get; init; }
    public int MpCost { get; init; }
    public int AccuracyBasisPoints { get; init; } = 10_000;
    public int CriticalBasisPoints { get; init; }
    public TargetRule TargetRule { get; init; }
    public List<BattleEffect> Effects { get; init; } = new();

    public void Validate()
    {
        if (string.IsNullOrWhiteSpace(Id) || Effects.Count == 0 || MpCost < 0 ||
            AccuracyBasisPoints is < 0 or > 10_000 ||
            CriticalBasisPoints is < 0 or > 10_000)
            throw new InvalidOperationException($"Invalid ability '{Id}'.");
    }
}

public sealed class StatusDefinition
{
    public required string Id { get; init; }
    public ushort DefaultDuration { get; init; } = 3;
    public byte MaxStacks { get; init; } = 1;
    public List<StatModifier> Modifiers { get; init; } = new();
    public List<BattleEffect> PeriodicEffects { get; init; } = new();
}

public sealed class ActiveStatus
{
    public ushort RemainingTurns { get; set; }
    public byte Stacks { get; set; }
}

public sealed class BattleUnit
{
    public required string Id { get; init; }
    public required string SourceId { get; init; }
    public BattleSide Side { get; init; }
    public StatBlock Stats { get; init; } = new();
    public int Hp { get; set; }
    public int Mp { get; set; }
    public uint Atb { get; set; }
    public bool Defending { get; set; }
    public ulong RewardExperience { get; init; }
    public ulong RewardCurrency { get; init; }
    public Dictionary<Element, int> ElementAffinityBasisPoints { get; init; } = new();
    public Dictionary<string, ActiveStatus> Statuses { get; init; } = new(StringComparer.Ordinal);

    [JsonIgnore]
    public bool Alive => Hp > 0;

    public static BattleUnit Create(string id, string sourceId, BattleSide side, StatBlock stats) =>
        new()
        {
            Id = id,
            SourceId = sourceId,
            Side = side,
            Stats = stats.Clamp(),
            Hp = stats.Clamp().MaxHp,
            Mp = stats.Clamp().MaxMp
        };

    public StatBlock ResolveStats(IReadOnlyDictionary<string, StatusDefinition> definitions)
    {
        var result = Stats;
        foreach (var (id, active) in Statuses)
            if (definitions.TryGetValue(id, out var definition))
                for (var stack = 0; stack < active.Stacks; stack++)
                    foreach (var modifier in definition.Modifiers)
                        result = result.Add(modifier.Flat);
        return result.Clamp();
    }
}

public sealed record BattleCommand(string ActorId, string AbilityId, IReadOnlyList<string> TargetIds);

public sealed record BattleEvent(
    string Type,
    string? SourceId = null,
    string? TargetId = null,
    string? DefinitionId = null,
    int Amount = 0,
    bool Critical = false);

public interface IBattleFormula
{
    int Damage(StatBlock attacker, StatBlock target, int power, DamageKind kind);
    int Healing(StatBlock caster, int power);
}

public sealed class ClassicBattleFormula : IBattleFormula
{
    public int Damage(StatBlock attacker, StatBlock target, int power, DamageKind kind)
    {
        if (kind == DamageKind.Direct) return Math.Max(0, power);
        var offense = kind == DamageKind.Physical ? attacker.Attack : attacker.Magic;
        var defense = kind == DamageKind.Physical ? target.Defense : target.Resistance;
        return Math.Max(1, SaturatingMultiply(offense, Math.Max(0, power)) / 100 - defense / 2);
    }

    public int Healing(StatBlock caster, int power) =>
        Math.Max(1, SaturatingMultiply(caster.Magic, Math.Max(0, power)) / 100);

    private static int SaturatingMultiply(int left, int right) =>
        (int)Math.Clamp((long)left * right, int.MinValue, int.MaxValue);
}

public sealed class BattleSession
{
    public BattlePhase Phase { get; private set; } = BattlePhase.Running;
    public uint AtbThreshold { get; init; } = 10_000;
    public Dictionary<string, BattleUnit> Units { get; init; } = new(StringComparer.Ordinal);
    public HashSet<string> Ready { get; init; } = new(StringComparer.Ordinal);
    public Queue<BattleCommand> Commands { get; init; } = new();

    public BattleSession() { }

    public BattleSession(IEnumerable<BattleUnit> units)
    {
        foreach (var unit in units)
            if (!Units.TryAdd(unit.Id, unit))
                throw new InvalidOperationException($"Duplicate battle unit '{unit.Id}'.");
        if (!Units.Values.Any(unit => unit.Side == BattleSide.Party) ||
            !Units.Values.Any(unit => unit.Side == BattleSide.Enemy))
            throw new InvalidOperationException("Battle requires party and enemy units.");
    }

    public IReadOnlyList<BattleEvent> AdvanceTime(uint deltaMilliseconds)
    {
        var events = new List<BattleEvent>();
        if (Phase != BattlePhase.Running) return events;
        foreach (var unit in Units.Values.OrderBy(unit => unit.Id, StringComparer.Ordinal))
        {
            if (!unit.Alive || Ready.Contains(unit.Id)) continue;
            unit.Atb = Math.Min(
                AtbThreshold,
                SaturatingAdd(unit.Atb, SaturatingMultiply((uint)Math.Max(1, unit.Stats.Speed), deltaMilliseconds)));
            if (unit.Atb >= AtbThreshold)
            {
                Ready.Add(unit.Id);
                events.Add(new BattleEvent("unit_ready", TargetId: unit.Id));
            }
        }
        return events;
    }

    public BattleEvent GrantTurn(string unitId)
    {
        var unit = GetUnit(unitId);
        if (!unit.Alive) throw new InvalidOperationException($"Unit '{unitId}' is defeated.");
        unit.Atb = AtbThreshold;
        Ready.Add(unitId);
        return new BattleEvent("unit_ready", TargetId: unitId);
    }

    public BattleEvent Queue(
        BattleCommand command,
        IReadOnlyDictionary<string, AbilityDefinition> abilities)
    {
        if (Phase != BattlePhase.Running) throw new InvalidOperationException("Battle has ended.");
        var actor = GetUnit(command.ActorId);
        if (!actor.Alive || !Ready.Contains(actor.Id))
            throw new InvalidOperationException($"Unit '{actor.Id}' is not ready.");
        if (!abilities.TryGetValue(command.AbilityId, out var ability))
            throw new KeyNotFoundException($"Unknown ability '{command.AbilityId}'.");
        ability.Validate();
        if (actor.Mp < ability.MpCost)
            throw new InvalidOperationException($"Unit '{actor.Id}' does not have enough MP.");
        if (!TargetsValid(actor, ability.TargetRule, command.TargetIds))
            throw new InvalidOperationException($"Invalid targets for '{ability.Id}'.");
        Ready.Remove(actor.Id);
        Commands.Enqueue(command);
        return new BattleEvent("command_queued", actor.Id, DefinitionId: ability.Id);
    }

    public IReadOnlyList<BattleEvent> ExecuteNext(
        IReadOnlyDictionary<string, AbilityDefinition> abilities,
        IReadOnlyDictionary<string, StatusDefinition> statuses,
        DeterministicRandom random,
        IBattleFormula? formula = null)
    {
        formula ??= new ClassicBattleFormula();
        var events = new List<BattleEvent>();
        if (Commands.Count == 0) return events;
        var command = Commands.Dequeue();
        var actor = GetUnit(command.ActorId);
        var ability = abilities[command.AbilityId];
        if (!actor.Alive) throw new InvalidOperationException($"Unit '{actor.Id}' is defeated.");
        actor.Mp -= ability.MpCost;
        if (ability.MpCost > 0)
            events.Add(new BattleEvent("mp_spent", actor.Id, Amount: ability.MpCost));
        var actorStats = actor.ResolveStats(statuses);
        foreach (var targetId in command.TargetIds)
            foreach (var effect in ability.Effects)
                ApplyEffect(actor, actorStats, GetUnit(targetId), ability, effect, statuses, random, formula, events);
        actor.Atb = 0;
        actor.Defending = false;
        TickStatuses(actor, statuses, random, formula, events);
        RefreshPhase(events);
        return events;
    }

    private void ApplyEffect(
        BattleUnit actor,
        StatBlock actorStats,
        BattleUnit target,
        AbilityDefinition ability,
        BattleEffect effect,
        IReadOnlyDictionary<string, StatusDefinition> statuses,
        DeterministicRandom random,
        IBattleFormula formula,
        List<BattleEvent> events)
    {
        switch (effect)
        {
            case DamageEffect damage:
                if (random.RollBasisPoints() >= ability.AccuracyBasisPoints)
                {
                    events.Add(new BattleEvent("missed", actor.Id, target.Id));
                    return;
                }
                var critical = random.RollBasisPoints() < ability.CriticalBasisPoints;
                var amount = formula.Damage(actorStats, target.ResolveStats(statuses), damage.Power, damage.Kind);
                amount = Scale(amount, target.ElementAffinityBasisPoints.GetValueOrDefault(damage.Element, 10_000));
                if (critical) amount = SaturatingMultiply(amount, 3) / 2;
                if (target.Defending) amount /= 2;
                target.Hp = Math.Max(0, target.Hp - amount);
                events.Add(new BattleEvent("damaged", actor.Id, target.Id, Amount: amount, Critical: critical));
                if (!target.Alive)
                {
                    target.Atb = 0;
                    Ready.Remove(target.Id);
                    events.Add(new BattleEvent("unit_defeated", actor.Id, target.Id));
                }
                break;
            case HealEffect heal:
                var before = target.Hp;
                target.Hp = Math.Min(target.Stats.MaxHp, target.Hp + formula.Healing(actorStats, heal.Power));
                events.Add(new BattleEvent("healed", actor.Id, target.Id, Amount: target.Hp - before));
                break;
            case RestoreMpEffect restore:
                target.Mp = Math.Clamp(target.Mp + restore.Amount, 0, target.Stats.MaxMp);
                break;
            case AddStatusEffect add:
                if (!statuses.TryGetValue(add.StatusId, out var status))
                    throw new KeyNotFoundException($"Unknown status '{add.StatusId}'.");
                if (random.RollBasisPoints() < Math.Clamp(add.ChanceBasisPoints, 0, 10_000))
                {
                    if (!target.Statuses.TryGetValue(add.StatusId, out var active))
                        target.Statuses[add.StatusId] = active = new ActiveStatus();
                    active.RemainingTurns = status.DefaultDuration;
                    active.Stacks = (byte)Math.Min(status.MaxStacks, active.Stacks + 1);
                    events.Add(new BattleEvent("status_added", actor.Id, target.Id, add.StatusId));
                }
                break;
            case RemoveStatusEffect remove:
                if (target.Statuses.Remove(remove.StatusId))
                    events.Add(new BattleEvent("status_removed", actor.Id, target.Id, remove.StatusId));
                break;
            case ReviveEffect revive when !target.Alive:
                target.Hp = Math.Max(1, Scale(target.Stats.MaxHp, Math.Clamp(revive.HealthBasisPoints, 0, 10_000)));
                events.Add(new BattleEvent("healed", actor.Id, target.Id, Amount: target.Hp));
                break;
        }
    }

    private void TickStatuses(
        BattleUnit unit,
        IReadOnlyDictionary<string, StatusDefinition> definitions,
        DeterministicRandom random,
        IBattleFormula formula,
        List<BattleEvent> events)
    {
        foreach (var (id, statusSnapshot) in unit.Statuses.ToArray())
        {
            if (!definitions.TryGetValue(id, out var definition))
                throw new KeyNotFoundException($"Unknown status '{id}'.");
            var periodic = new AbilityDefinition
            {
                Id = $"status.{id}",
                DisplayNameKey = id,
                TargetRule = TargetRule.SelfUnit,
                Effects = definition.PeriodicEffects
            };
            for (var stack = 0; stack < statusSnapshot.Stacks; stack++)
                foreach (var effect in definition.PeriodicEffects)
                    ApplyEffect(unit, unit.ResolveStats(definitions), unit, periodic, effect, definitions, random, formula, events);
            if (!unit.Statuses.TryGetValue(id, out var active)) continue;
            if (active.RemainingTurns > 0) active.RemainingTurns--;
            if (active.RemainingTurns == 0)
            {
                unit.Statuses.Remove(id);
                events.Add(new BattleEvent("status_removed", unit.Id, unit.Id, id));
            }
        }
    }

    private bool TargetsValid(BattleUnit actor, TargetRule rule, IReadOnlyList<string> ids)
    {
        if (ids.Count == 0 || ids.Distinct(StringComparer.Ordinal).Count() != ids.Count ||
            ids.Any(id => !Units.ContainsKey(id))) return false;
        var targets = ids.Select(GetUnit).ToList();
        var livingAllies = Units.Values.Count(unit => unit.Side == actor.Side && unit.Alive);
        var livingEnemies = Units.Values.Count(unit => unit.Side != actor.Side && unit.Alive);
        return rule switch
        {
            TargetRule.SelfUnit => ids.Count == 1 && ids[0] == actor.Id,
            TargetRule.SingleAlly => targets.Count == 1 && targets[0].Side == actor.Side && targets[0].Alive,
            TargetRule.AllAllies => targets.Count == livingAllies && targets.All(unit => unit.Side == actor.Side && unit.Alive),
            TargetRule.SingleEnemy => targets.Count == 1 && targets[0].Side != actor.Side && targets[0].Alive,
            TargetRule.AllEnemies => targets.Count == livingEnemies && targets.All(unit => unit.Side != actor.Side && unit.Alive),
            TargetRule.AnySingle => targets.Count == 1,
            _ => false
        };
    }

    private void RefreshPhase(List<BattleEvent> events)
    {
        var party = Units.Values.Any(unit => unit.Side == BattleSide.Party && unit.Alive);
        var enemy = Units.Values.Any(unit => unit.Side == BattleSide.Enemy && unit.Alive);
        var next = party && enemy ? BattlePhase.Running :
            party ? BattlePhase.PartyVictory : BattlePhase.EnemyVictory;
        if (next != Phase)
        {
            Phase = next;
            events.Add(new BattleEvent("phase_changed", DefinitionId: next.ToString()));
        }
    }

    private BattleUnit GetUnit(string id) => Units.TryGetValue(id, out var unit)
        ? unit
        : throw new KeyNotFoundException($"Unknown battle unit '{id}'.");

    private static uint SaturatingAdd(uint left, uint right) =>
        uint.MaxValue - left < right ? uint.MaxValue : left + right;
    private static uint SaturatingMultiply(uint left, uint right) =>
        left == 0 || right <= uint.MaxValue / left ? left * right : uint.MaxValue;
    private static int SaturatingMultiply(int left, int right) =>
        (int)Math.Clamp((long)left * right, int.MinValue, int.MaxValue);
    private static int Scale(int value, int basisPoints) =>
        (int)Math.Clamp((long)value * Math.Clamp(basisPoints, -20_000, 20_000) / 10_000, int.MinValue, int.MaxValue);
}

public enum QuestStatus { Inactive, Active, Completed, Failed }

public sealed class QuestObjective
{
    public required string Id { get; init; }
    public required string TextKey { get; init; }
    public uint TargetCount { get; init; } = 1;
}

public sealed class QuestDefinition
{
    public required string Id { get; init; }
    public required string TitleKey { get; init; }
    public required string DescriptionKey { get; init; }
    public List<QuestObjective> Objectives { get; init; } = new();
}

public sealed class QuestProgress
{
    public QuestStatus Status { get; set; }
    public Dictionary<string, uint> ObjectiveCounts { get; init; } = new(StringComparer.Ordinal);
}

public sealed class QuestJournal
{
    public Dictionary<string, QuestProgress> Quests { get; init; } = new(StringComparer.Ordinal);

    public void Start(QuestDefinition definition)
    {
        var progress = Quests.GetValueOrDefault(definition.Id) ?? new QuestProgress();
        progress.Status = QuestStatus.Active;
        foreach (var objective in definition.Objectives)
            progress.ObjectiveCounts.TryAdd(objective.Id, 0);
        Quests[definition.Id] = progress;
    }

    public bool Advance(QuestDefinition definition, string objectiveId, uint amount = 1)
    {
        if (!Quests.TryGetValue(definition.Id, out var progress) ||
            progress.Status != QuestStatus.Active)
            throw new InvalidOperationException($"Quest '{definition.Id}' is not active.");
        var objective = definition.Objectives.FirstOrDefault(item => item.Id == objectiveId) ??
            throw new KeyNotFoundException($"Unknown objective '{objectiveId}'.");
        progress.ObjectiveCounts[objectiveId] = Math.Min(
            objective.TargetCount,
            SaturatingAdd(progress.ObjectiveCounts.GetValueOrDefault(objectiveId), amount));
        return definition.Objectives.All(item =>
            progress.ObjectiveCounts.GetValueOrDefault(item.Id) >= item.TargetCount);
    }

    public void Complete(QuestDefinition definition)
    {
        if (!Quests.TryGetValue(definition.Id, out var progress) ||
            !definition.Objectives.All(item =>
                progress.ObjectiveCounts.GetValueOrDefault(item.Id) >= item.TargetCount))
            throw new InvalidOperationException($"Quest '{definition.Id}' has incomplete objectives.");
        progress.Status = QuestStatus.Completed;
    }

    private static uint SaturatingAdd(uint left, uint right) =>
        uint.MaxValue - left < right ? uint.MaxValue : left + right;
}

public sealed class StoryState
{
    public Dictionary<string, JsonElement> Flags { get; init; } = new(StringComparer.Ordinal);
    public QuestJournal Journal { get; init; } = new();

    public void Set<T>(string key, T value) =>
        Flags[key] = JsonSerializer.SerializeToElement(value, JrpgJson.Options);

    public T Get<T>(string key, T fallback = default!) =>
        Flags.TryGetValue(key, out var value)
            ? value.Deserialize<T>(JrpgJson.Options)!
            : fallback;
}

public sealed record DialogueChoice(
    string TextKey,
    string Next,
    string? RequiredBoolFlag = null,
    bool RequiredBoolValue = true);

public sealed class DialogueNode
{
    public required string Type { get; init; }
    public string? SpeakerId { get; init; }
    public string? TextKey { get; init; }
    public string? VoiceAsset { get; init; }
    public string? PortraitAsset { get; init; }
    public string? Next { get; init; }
    public List<DialogueChoice> Choices { get; init; } = new();
}

public sealed class DialogueGraph
{
    public required string Id { get; init; }
    public required string Entry { get; init; }
    public Dictionary<string, DialogueNode> Nodes { get; init; } = new(StringComparer.Ordinal);
}

public sealed record DialogueBeat(
    string Type,
    string? SpeakerId = null,
    string? TextKey = null,
    string? VoiceAsset = null,
    string? PortraitAsset = null,
    IReadOnlyList<(int Index, string TextKey)>? Choices = null);

public sealed class DialogueRunner
{
    public required string GraphId { get; init; }
    public required string CurrentNode { get; set; }
    public string? PendingNext { get; set; }

    public static DialogueRunner Start(DialogueGraph graph) =>
        new() { GraphId = graph.Id, CurrentNode = graph.Entry };

    public DialogueBeat Beat(DialogueGraph graph, StoryState story)
    {
        var node = graph.Nodes.GetValueOrDefault(CurrentNode) ??
            throw new KeyNotFoundException($"Unknown dialogue node '{CurrentNode}'.");
        return node.Type switch
        {
            "line" => Line(node),
            "choice" => new DialogueBeat(
                "choices",
                TextKey: node.TextKey,
                Choices: node.Choices
                    .Select((choice, index) => (choice, index))
                    .Where(pair => pair.choice.RequiredBoolFlag == null ||
                        story.Get(pair.choice.RequiredBoolFlag, false) == pair.choice.RequiredBoolValue)
                    .Select(pair => (pair.index, pair.choice.TextKey))
                    .ToList()),
            "end" => new DialogueBeat("end"),
            _ => throw new InvalidOperationException($"Unsupported dialogue node type '{node.Type}'.")
        };
    }

    public void AdvanceLine()
    {
        CurrentNode = PendingNext ??
            throw new InvalidOperationException("Dialogue is not waiting on a line.");
        PendingNext = null;
    }

    public void Choose(DialogueGraph graph, StoryState story, int index)
    {
        var node = graph.Nodes.GetValueOrDefault(CurrentNode) ??
            throw new KeyNotFoundException($"Unknown dialogue node '{CurrentNode}'.");
        if (node.Type != "choice" || index < 0 || index >= node.Choices.Count)
            throw new InvalidOperationException("Dialogue is not waiting on that choice.");
        var choice = node.Choices[index];
        if (choice.RequiredBoolFlag != null &&
            story.Get(choice.RequiredBoolFlag, false) != choice.RequiredBoolValue)
            throw new InvalidOperationException("Dialogue choice is unavailable.");
        CurrentNode = choice.Next;
    }

    private DialogueBeat Line(DialogueNode node)
    {
        PendingNext = node.Next ??
            throw new InvalidOperationException("Dialogue line has no next node.");
        return new DialogueBeat(
            "line",
            node.SpeakerId,
            node.TextKey,
            node.VoiceAsset,
            node.PortraitAsset);
    }
}

public sealed class EnemyFormation
{
    public required string Id { get; init; }
    public List<string> EnemyIds { get; init; } = new();
    public uint Weight { get; init; } = 1;
    public string? BattleScene { get; init; }
    public string? BattleMusic { get; init; }
}

public sealed class EncounterTable
{
    public required string Id { get; init; }
    public List<EnemyFormation> Formations { get; init; } = new();

    public EnemyFormation Choose(DeterministicRandom random)
    {
        var table = new WeightedTable<EnemyFormation>();
        foreach (var formation in Formations)
            if (formation.Weight > 0) table.Add(formation, formation.Weight);
        return table.Choose(random);
    }
}

public sealed class EncounterMeter
{
    public uint Progress { get; set; }
    public uint Threshold { get; init; } = 10_000;
    public bool Disabled { get; set; }

    public bool Advance(uint amount)
    {
        if (Threshold == 0) throw new InvalidOperationException("Encounter threshold is zero.");
        if (Disabled) return false;
        Progress = uint.MaxValue - Progress < amount ? uint.MaxValue : Progress + amount;
        if (Progress < Threshold) return false;
        Progress %= Threshold;
        return true;
    }
}

public sealed class LocalizationCatalog
{
    public required string FallbackLocale { get; init; }
    public Dictionary<string, Dictionary<string, string>> Locales { get; init; } =
        new(StringComparer.Ordinal);

    public string Resolve(
        string locale,
        string key,
        IReadOnlyDictionary<string, string>? tokens = null)
    {
        string? template = null;
        if (Locales.TryGetValue(locale, out var selected))
            selected.TryGetValue(key, out template);
        if (template == null && Locales.TryGetValue(FallbackLocale, out var fallback))
            fallback.TryGetValue(key, out template);
        if (template == null)
            throw new KeyNotFoundException($"Missing localization key '{key}' for '{locale}'.");
        if (tokens == null) return template;
        var result = template;
        foreach (var (token, value) in tokens.OrderBy(pair => pair.Key, StringComparer.Ordinal))
            result = result.Replace($"{{{token}}}", value, StringComparison.Ordinal);
        return result;
    }
}

[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
[JsonDerivedType(typeof(PlaySequenceAnimation), "play_animation")]
[JsonDerivedType(typeof(PlaySequenceAudio), "play_audio")]
[JsonDerivedType(typeof(ActivateSequenceCamera), "activate_camera")]
[JsonDerivedType(typeof(FadeSequence), "fade")]
[JsonDerivedType(typeof(StartSequenceDialogue), "start_dialogue")]
[JsonDerivedType(typeof(LoadSequenceScene), "load_scene")]
[JsonDerivedType(typeof(CustomSequenceCommand), "custom")]
public abstract record SequenceCommand;
public sealed record PlaySequenceAnimation(
    string EntityId,
    string ClipAsset,
    bool Looping = false,
    float Speed = 1.0f) : SequenceCommand;
public sealed record PlaySequenceAudio(
    string EntityId,
    string ClipAsset,
    float Volume = 1.0f,
    bool Looping = false) : SequenceCommand;
public sealed record ActivateSequenceCamera(string CameraEntityId, uint BlendMilliseconds = 0) :
    SequenceCommand;
public sealed record FadeSequence(float From, float To, uint DurationMilliseconds) : SequenceCommand;
public sealed record StartSequenceDialogue(string DialogueId) : SequenceCommand;
public sealed record LoadSequenceScene(string SceneId) : SequenceCommand;
public sealed record CustomSequenceCommand(
    string Command,
    IReadOnlyDictionary<string, JsonElement>? Payload = null) : SequenceCommand;

[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
[JsonDerivedType(typeof(WaitSequenceStep), "wait")]
[JsonDerivedType(typeof(EmitSequenceStep), "emit")]
public abstract record SequenceStep;
public sealed record WaitSequenceStep(uint DurationMilliseconds) : SequenceStep;
public sealed record EmitSequenceStep(SequenceCommand Command) : SequenceStep;

public sealed class SequenceDefinition
{
    public required string Id { get; init; }
    public List<SequenceStep> Steps { get; init; } = new();
}

public sealed class SequenceRunner
{
    public required string SequenceId { get; init; }
    public int NextStep { get; set; }
    public uint WaitRemainingMilliseconds { get; set; }
    public bool Finished { get; set; }

    public static SequenceRunner Start(SequenceDefinition sequence) =>
        new() { SequenceId = sequence.Id, Finished = sequence.Steps.Count == 0 };

    public IReadOnlyList<SequenceCommand> Advance(
        SequenceDefinition sequence,
        uint deltaMilliseconds)
    {
        var commands = new List<SequenceCommand>();
        if (Finished || SequenceId != sequence.Id) return commands;
        while (true)
        {
            if (WaitRemainingMilliseconds > 0)
            {
                var consumed = Math.Min(deltaMilliseconds, WaitRemainingMilliseconds);
                WaitRemainingMilliseconds -= consumed;
                deltaMilliseconds -= consumed;
                if (WaitRemainingMilliseconds > 0) break;
            }
            if (NextStep >= sequence.Steps.Count)
            {
                Finished = true;
                break;
            }
            switch (sequence.Steps[NextStep++])
            {
                case WaitSequenceStep wait:
                    WaitRemainingMilliseconds = wait.DurationMilliseconds;
                    if (deltaMilliseconds == 0 && WaitRemainingMilliseconds > 0)
                        return commands;
                    break;
                case EmitSequenceStep emit:
                    commands.Add(emit.Command);
                    break;
            }
        }
        return commands;
    }
}

public sealed class ActorDefinition
{
    public required string Id { get; init; }
    public required string DisplayNameKey { get; init; }
    public StatBlock BaseStats { get; init; } = new();
    public List<string> StartingAbilities { get; init; } = new();
    public string? FieldPrefab { get; init; }
    public string? BattlePrefab { get; init; }
}

public sealed class EnemyDefinition
{
    public required string Id { get; init; }
    public required string DisplayNameKey { get; init; }
    public StatBlock Stats { get; init; } = new();
    public List<string> Abilities { get; init; } = new();
    public ulong RewardExperience { get; init; }
    public ulong RewardCurrency { get; init; }
    public string? BattlePrefab { get; init; }
}

public sealed class JrpgDatabase
{
    public Dictionary<string, ActorDefinition> Actors { get; init; } = new(StringComparer.Ordinal);
    public Dictionary<string, EnemyDefinition> Enemies { get; init; } = new(StringComparer.Ordinal);
    public Dictionary<string, ItemDefinition> Items { get; init; } = new(StringComparer.Ordinal);
    public Dictionary<string, AbilityDefinition> Abilities { get; init; } = new(StringComparer.Ordinal);
    public Dictionary<string, StatusDefinition> Statuses { get; init; } = new(StringComparer.Ordinal);
    public Dictionary<string, QuestDefinition> Quests { get; init; } = new(StringComparer.Ordinal);
    public Dictionary<string, DialogueGraph> Dialogues { get; init; } = new(StringComparer.Ordinal);
    public Dictionary<string, EncounterTable> Encounters { get; init; } = new(StringComparer.Ordinal);
    public Dictionary<string, LocalizationCatalog> Localizations { get; init; } =
        new(StringComparer.Ordinal);
    public Dictionary<string, SequenceDefinition> Sequences { get; init; } =
        new(StringComparer.Ordinal);

    public static JrpgDatabase FromJson(string json)
    {
        var database = JsonSerializer.Deserialize<JrpgDatabase>(json, JrpgJson.Options) ??
            throw new InvalidOperationException("JRPG database JSON produced null.");
        database.Validate();
        return database;
    }

    public void Validate()
    {
        ValidateKeys(Actors, item => item.Id, "actor");
        ValidateKeys(Enemies, item => item.Id, "enemy");
        ValidateKeys(Items, item => item.Id, "item");
        ValidateKeys(Abilities, item => item.Id, "ability");
        ValidateKeys(Statuses, item => item.Id, "status");
        ValidateKeys(Quests, item => item.Id, "quest");
        ValidateKeys(Dialogues, item => item.Id, "dialogue");
        ValidateKeys(Encounters, item => item.Id, "encounter");
        ValidateKeys(Sequences, item => item.Id, "sequence");
        foreach (var item in Items.Values)
        {
            item.Validate();
            if (item.ConsumableAbility != null)
                Require(Abilities, item.ConsumableAbility, $"item '{item.Id}' ability");
            if (item.Equipment != null)
                foreach (var ability in item.Equipment.GrantedAbilities)
                    Require(Abilities, ability, $"item '{item.Id}' ability");
        }
        foreach (var ability in Abilities.Values)
        {
            ability.Validate();
            foreach (var effect in ability.Effects)
                ValidateEffect(effect, $"ability '{ability.Id}'");
        }
        foreach (var status in Statuses.Values)
        {
            if (status.DefaultDuration == 0 || status.MaxStacks == 0)
                throw new InvalidOperationException($"Invalid status '{status.Id}'.");
            foreach (var effect in status.PeriodicEffects)
                ValidateEffect(effect, $"status '{status.Id}'");
        }
        foreach (var actor in Actors.Values)
            foreach (var ability in actor.StartingAbilities)
                Require(Abilities, ability, $"actor '{actor.Id}' ability");
        foreach (var enemy in Enemies.Values)
            foreach (var ability in enemy.Abilities)
                Require(Abilities, ability, $"enemy '{enemy.Id}' ability");
        foreach (var table in Encounters.Values)
        {
            if (table.Formations.Select(item => item.Id).Distinct(StringComparer.Ordinal).Count() !=
                table.Formations.Count)
                throw new InvalidOperationException($"Encounter '{table.Id}' has duplicate formations.");
            foreach (var formation in table.Formations)
            {
                if (formation.Weight == 0 || formation.EnemyIds.Count == 0)
                    throw new InvalidOperationException($"Invalid formation '{formation.Id}'.");
                foreach (var enemy in formation.EnemyIds)
                    Require(Enemies, enemy, $"formation '{formation.Id}' enemy");
            }
        }
        foreach (var quest in Quests.Values)
        {
            if (quest.Objectives.Any(item => item.TargetCount == 0) ||
                quest.Objectives.Select(item => item.Id).Distinct(StringComparer.Ordinal).Count() !=
                quest.Objectives.Count)
                throw new InvalidOperationException($"Quest '{quest.Id}' has invalid objectives.");
        }
        foreach (var graph in Dialogues.Values)
        {
            if (!graph.Nodes.ContainsKey(graph.Entry))
                throw new InvalidOperationException($"Dialogue '{graph.Id}' has no entry node.");
            foreach (var node in graph.Nodes.Values)
            {
                IEnumerable<string> next = node.Type == "choice"
                    ? node.Choices.Select(choice => choice.Next)
                    : node.Next == null ? Array.Empty<string>() : new[] { node.Next };
                foreach (var nodeId in next)
                    if (!graph.Nodes.ContainsKey(nodeId))
                        throw new InvalidOperationException(
                            $"Dialogue '{graph.Id}' references missing node '{nodeId}'.");
            }
        }
        foreach (var (id, catalog) in Localizations)
            if (string.IsNullOrEmpty(catalog.FallbackLocale) ||
                !catalog.Locales.ContainsKey(catalog.FallbackLocale))
                throw new InvalidOperationException(
                    $"Localization '{id}' has no fallback locale '{catalog.FallbackLocale}'.");
        foreach (var sequence in Sequences.Values)
            foreach (var step in sequence.Steps.OfType<EmitSequenceStep>())
                ValidateSequenceCommand(sequence.Id, step.Command);
    }

    private void ValidateEffect(BattleEffect effect, string owner)
    {
        switch (effect)
        {
            case DamageEffect damage when damage.Power <= 0:
            case HealEffect heal when heal.Power <= 0:
                throw new InvalidOperationException($"{owner} has non-positive effect power.");
            case AddStatusEffect add:
                if (add.ChanceBasisPoints is < 0 or > 10_000)
                    throw new InvalidOperationException($"{owner} has an invalid status chance.");
                Require(Statuses, add.StatusId, $"{owner} status");
                break;
            case RemoveStatusEffect remove:
                Require(Statuses, remove.StatusId, $"{owner} status");
                break;
            case ReviveEffect revive when revive.HealthBasisPoints is <= 0 or > 10_000:
                throw new InvalidOperationException($"{owner} has an invalid revive percentage.");
        }
    }

    private static void ValidateSequenceCommand(string sequenceId, SequenceCommand command)
    {
        var valid = command switch
        {
            PlaySequenceAnimation item =>
                !string.IsNullOrEmpty(item.EntityId) && !string.IsNullOrEmpty(item.ClipAsset) &&
                float.IsFinite(item.Speed) && item.Speed > 0.0f,
            PlaySequenceAudio item =>
                !string.IsNullOrEmpty(item.EntityId) && !string.IsNullOrEmpty(item.ClipAsset) &&
                float.IsFinite(item.Volume) && item.Volume is >= 0.0f and <= 1.0f,
            ActivateSequenceCamera item => !string.IsNullOrEmpty(item.CameraEntityId),
            FadeSequence item =>
                float.IsFinite(item.From) && float.IsFinite(item.To) &&
                item.From is >= 0.0f and <= 1.0f && item.To is >= 0.0f and <= 1.0f,
            StartSequenceDialogue item => !string.IsNullOrEmpty(item.DialogueId),
            LoadSequenceScene item => !string.IsNullOrEmpty(item.SceneId),
            CustomSequenceCommand item => !string.IsNullOrEmpty(item.Command),
            _ => false
        };
        if (!valid)
            throw new InvalidOperationException($"Sequence '{sequenceId}' contains an invalid command.");
    }

    private static void ValidateKeys<T>(
        IReadOnlyDictionary<string, T> values,
        Func<T, string> id,
        string kind)
    {
        foreach (var (key, value) in values)
            if (key != id(value))
                throw new InvalidOperationException($"{kind} key '{key}' does not match '{id(value)}'.");
    }

    private static void Require<T>(IReadOnlyDictionary<string, T> values, string id, string owner)
    {
        if (!values.ContainsKey(id))
            throw new InvalidOperationException($"{owner} references missing '{id}'.");
    }
}

public sealed class JrpgSession
{
    public const int CurrentSchemaVersion = 1;

    public int SchemaVersion { get; init; } = CurrentSchemaVersion;
    public Party Party { get; init; } = new();
    public Inventory Inventory { get; init; } = new();
    public StoryState Story { get; init; } = new();
    public Dictionary<string, EncounterMeter> EncounterMeters { get; init; } = new(StringComparer.Ordinal);
    public BattleSession? Battle { get; set; }
    public DeterministicRandom Random { get; init; }

    public JrpgSession(ulong seed = 0) => Random = new DeterministicRandom(seed);

    public string ToJson() => JsonSerializer.Serialize(this, JrpgJson.Options);

    public static JrpgSession FromJson(string json)
    {
        var session = JsonSerializer.Deserialize<JrpgSession>(json, JrpgJson.Options) ??
            throw new InvalidOperationException("JRPG session JSON produced null.");
        if (session.SchemaVersion != CurrentSchemaVersion)
            throw new InvalidOperationException($"Unsupported JRPG schema {session.SchemaVersion}.");
        return session;
    }

    public void Recruit(JrpgDatabase database, string actorId, bool preferActive = true)
    {
        var definition = database.Actors.GetValueOrDefault(actorId) ??
            throw new KeyNotFoundException($"Unknown actor '{actorId}'.");
        var actor = new CharacterProgress
        {
            ActorId = definition.Id,
            DisplayNameKey = definition.DisplayNameKey,
            BaseStats = definition.BaseStats.Clamp()
        };
        actor.LearnedAbilities.UnionWith(definition.StartingAbilities);
        Party.Recruit(actor, preferActive);
    }
}

/// Convenience adapters between the pure JRPG state and the frame-safe script bridge.
public static class JrpgScriptTools
{
    public static LogicAssetQuery QueryDatabase(EngineBehaviour behaviour, string assetId) =>
        behaviour.LogicAssets.Query(assetId);

    public static bool TryGetDatabase(
        EngineBehaviour behaviour,
        LogicAssetQuery query,
        out JrpgDatabase database)
    {
        if (behaviour.LogicAssets.TryGetJson(query, out var json))
        {
            database = JrpgDatabase.FromJson(json);
            return true;
        }
        database = null!;
        return false;
    }

    public static void SaveSession(
        EngineBehaviour behaviour,
        string slot,
        JrpgSession session) =>
        behaviour.Save.SaveJson(slot, session.ToJson());

    public static bool TryRestoreSession(
        EngineBehaviour behaviour,
        string slot,
        out JrpgSession session)
    {
        if (behaviour.Save.TryGetLoadedJson(slot, out var json))
        {
            session = JrpgSession.FromJson(json);
            return true;
        }
        session = null!;
        return false;
    }

    /// Executes sequence commands backed by existing engine APIs. Camera
    /// blends, fades, dialogue UI, and custom commands intentionally return
    /// false so the project can route them through its presentation layer.
    public static bool TryExecuteSequenceCommand(
        EngineBehaviour behaviour,
        SequenceCommand command)
    {
        switch (command)
        {
            case PlaySequenceAnimation animation:
                behaviour.Animation.PlayClip(
                    animation.EntityId,
                    animation.ClipAsset,
                    animation.Looping,
                    animation.Speed);
                return true;
            case PlaySequenceAudio audio:
                behaviour.Audio.Play(
                    audio.EntityId,
                    audio.ClipAsset,
                    audio.Volume,
                    audio.Looping);
                return true;
            case LoadSequenceScene scene:
                behaviour.Scene.Load(scene.SceneId);
                return true;
            default:
                return false;
        }
    }
}
