// <auto-generated>
// Engine-owned tactical-game toolkit. Game-specific rules should compose these
// services through their strategy interfaces instead of modifying this file.
// </auto-generated>
#nullable enable
using System.Text.Json;
using System.Text.Json.Serialization;
using Engine.Gameplay;

namespace Engine.Tactics;

public readonly record struct GridCoord(int X, int Y, int Level = 0) : IComparable<GridCoord>
{
    public int ManhattanDistance(GridCoord other) =>
        Math.Abs(X - other.X) + Math.Abs(Y - other.Y) + Math.Abs(Level - other.Level) * 2;

    public GridCoord Offset(CardinalDirection direction) => direction switch
    {
        CardinalDirection.North => this with { Y = Y + 1 },
        CardinalDirection.East => this with { X = X + 1 },
        CardinalDirection.South => this with { Y = Y - 1 },
        CardinalDirection.West => this with { X = X - 1 },
        _ => this,
    };

    public int CompareTo(GridCoord other)
    {
        var level = Level.CompareTo(other.Level);
        if (level != 0) return level;
        var y = Y.CompareTo(other.Y);
        return y != 0 ? y : X.CompareTo(other.X);
    }
}

public enum CardinalDirection { North, East, South, West }
public enum CoverKind { None, Half, Full }
public enum VisibilityState { Unseen, Explored, Visible }

public sealed class TacticalCell
{
    public GridCoord Coord { get; init; }
    public Vector3 WorldPosition { get; set; }
    public int MovementCost { get; set; } = 1;
    public bool Walkable { get; set; } = true;
    public bool BlocksSight { get; set; }
    public Dictionary<CardinalDirection, CoverKind> Cover { get; init; } = new();

    public CoverKind CoverAt(CardinalDirection direction) =>
        Cover.TryGetValue(direction, out var cover) ? cover : CoverKind.None;
}

public readonly record struct BoardOccupant(GridCoord Coord, string EntityId);
public readonly record struct BoardLink(GridCoord From, GridCoord To);

public sealed class TacticalBoardSnapshot
{
    public List<TacticalCell> Cells { get; init; } = new();
    public List<BoardOccupant> Occupants { get; init; } = new();
    public List<BoardOccupant> Reservations { get; init; } = new();
    public List<BoardLink> Links { get; init; } = new();
}

/// Owns all tactical spatial invariants: cells, occupancy, reservations and
/// explicit traversal links.
public sealed class TacticalBoard
{
    private readonly Dictionary<GridCoord, TacticalCell> _cells = new();
    private readonly Dictionary<GridCoord, string> _occupants = new();
    private readonly Dictionary<string, GridCoord> _positions = new(StringComparer.Ordinal);
    private readonly Dictionary<GridCoord, string> _reservations = new();
    private readonly Dictionary<GridCoord, SortedSet<GridCoord>> _links = new();

    public IEnumerable<TacticalCell> Cells => _cells.Values.OrderBy(cell => cell.Coord);

    public void AddOrReplaceCell(TacticalCell cell) => _cells[cell.Coord] = cell;

    public bool TryGetCell(GridCoord coord, out TacticalCell cell) =>
        _cells.TryGetValue(coord, out cell!);

    public TacticalCell GetCell(GridCoord coord) =>
        _cells.TryGetValue(coord, out var cell)
            ? cell
            : throw new KeyNotFoundException($"Tactical cell {coord} does not exist.");

    public string? OccupantAt(GridCoord coord) =>
        _occupants.TryGetValue(coord, out var entity) ? entity : null;

    public GridCoord? PositionOf(string entityId) =>
        _positions.TryGetValue(entityId, out var coord) ? coord : null;

    public bool CanEnter(GridCoord coord, string? entityId = null)
    {
        if (!_cells.TryGetValue(coord, out var cell) || !cell.Walkable) return false;
        if (_occupants.TryGetValue(coord, out var occupant) &&
            !StringComparer.Ordinal.Equals(occupant, entityId)) return false;
        return !_reservations.TryGetValue(coord, out var owner) ||
               StringComparer.Ordinal.Equals(owner, entityId);
    }

    public void Place(string entityId, GridCoord coord)
    {
        RequireEnterable(entityId, coord);
        if (_positions.Remove(entityId, out var previous)) _occupants.Remove(previous);
        _positions[entityId] = coord;
        _occupants[coord] = entityId;
    }

    public void Move(string entityId, GridCoord coord)
    {
        if (!_positions.ContainsKey(entityId))
            throw new InvalidOperationException($"Tactical entity '{entityId}' is not on the board.");
        Place(entityId, coord);
    }

    public bool Remove(string entityId)
    {
        if (!_positions.Remove(entityId, out var coord)) return false;
        _occupants.Remove(coord);
        ReleaseReservations(entityId);
        return true;
    }

    public void Reserve(string entityId, GridCoord coord)
    {
        RequireEnterable(entityId, coord);
        ReleaseReservations(entityId);
        _reservations[coord] = entityId;
    }

    public void ReleaseReservations(string entityId)
    {
        foreach (var coord in _reservations
                     .Where(pair => StringComparer.Ordinal.Equals(pair.Value, entityId))
                     .Select(pair => pair.Key)
                     .ToArray())
            _reservations.Remove(coord);
    }

    public void AddLink(GridCoord from, GridCoord to, bool bidirectional = true)
    {
        GetCell(from);
        GetCell(to);
        LinkOneWay(from, to);
        if (bidirectional) LinkOneWay(to, from);
    }

    public IEnumerable<GridCoord> Neighbors(GridCoord coord)
    {
        var result = new SortedSet<GridCoord>();
        foreach (var direction in Enum.GetValues<CardinalDirection>())
        {
            var neighbor = coord.Offset(direction);
            if (_cells.ContainsKey(neighbor)) result.Add(neighbor);
        }
        if (_links.TryGetValue(coord, out var links)) result.UnionWith(links);
        return result;
    }

    public CoverKind CoverBetween(GridCoord from, GridCoord to)
    {
        var direction = DirectionBetween(from, to);
        if (direction is null) return CoverKind.None;
        var left = GetCell(from).CoverAt(direction.Value);
        var right = GetCell(to).CoverAt(Opposite(direction.Value));
        return (CoverKind)Math.Max((int)left, (int)right);
    }

    public TacticalBoardSnapshot CreateSnapshot() => new()
    {
        Cells = Cells.Select(CloneCell).ToList(),
        Occupants = _occupants
            .OrderBy(pair => pair.Key)
            .Select(pair => new BoardOccupant(pair.Key, pair.Value))
            .ToList(),
        Reservations = _reservations
            .OrderBy(pair => pair.Key)
            .Select(pair => new BoardOccupant(pair.Key, pair.Value))
            .ToList(),
        Links = _links
            .SelectMany(pair => pair.Value
                .Where(to => pair.Key.CompareTo(to) <= 0)
                .Select(to => new BoardLink(pair.Key, to)))
            .OrderBy(link => link.From)
            .ThenBy(link => link.To)
            .ToList(),
    };

    public static TacticalBoard FromSnapshot(TacticalBoardSnapshot snapshot)
    {
        var board = new TacticalBoard();
        foreach (var cell in snapshot.Cells) board.AddOrReplaceCell(CloneCell(cell));
        foreach (var link in snapshot.Links) board.AddLink(link.From, link.To);
        foreach (var occupant in snapshot.Occupants) board.Place(occupant.EntityId, occupant.Coord);
        foreach (var reservation in snapshot.Reservations)
            board.Reserve(reservation.EntityId, reservation.Coord);
        return board;
    }

    private void RequireEnterable(string entityId, GridCoord coord)
    {
        if (!_cells.TryGetValue(coord, out var cell))
            throw new KeyNotFoundException($"Tactical cell {coord} does not exist.");
        if (!cell.Walkable) throw new InvalidOperationException($"Tactical cell {coord} is blocked.");
        if (_occupants.TryGetValue(coord, out var occupant) &&
            !StringComparer.Ordinal.Equals(occupant, entityId))
            throw new InvalidOperationException($"Tactical cell {coord} is occupied by '{occupant}'.");
        if (_reservations.TryGetValue(coord, out var owner) &&
            !StringComparer.Ordinal.Equals(owner, entityId))
            throw new InvalidOperationException($"Tactical cell {coord} is reserved by '{owner}'.");
    }

    private void LinkOneWay(GridCoord from, GridCoord to)
    {
        if (!_links.TryGetValue(from, out var links))
            _links[from] = links = new SortedSet<GridCoord>();
        links.Add(to);
    }

    private static TacticalCell CloneCell(TacticalCell cell) => new()
    {
        Coord = cell.Coord,
        WorldPosition = cell.WorldPosition,
        MovementCost = cell.MovementCost,
        Walkable = cell.Walkable,
        BlocksSight = cell.BlocksSight,
        Cover = new Dictionary<CardinalDirection, CoverKind>(cell.Cover),
    };

    private static CardinalDirection? DirectionBetween(GridCoord from, GridCoord to)
    {
        if (from.Level != to.Level) return null;
        foreach (var direction in Enum.GetValues<CardinalDirection>())
            if (from.Offset(direction) == to) return direction;
        return null;
    }

    private static CardinalDirection Opposite(CardinalDirection direction) => direction switch
    {
        CardinalDirection.North => CardinalDirection.South,
        CardinalDirection.East => CardinalDirection.West,
        CardinalDirection.South => CardinalDirection.North,
        _ => CardinalDirection.East,
    };
}

public interface IMovementCostPolicy
{
    int? StepCost(TacticalBoard board, GridCoord from, GridCoord to, string? actorId);
}

public sealed class DefaultMovementCostPolicy : IMovementCostPolicy
{
    public int? StepCost(TacticalBoard board, GridCoord from, GridCoord to, string? actorId)
    {
        if (!board.CanEnter(to, actorId)) return null;
        return Math.Max(1, board.GetCell(to).MovementCost);
    }
}

public sealed class TacticalPath
{
    public IReadOnlyList<GridCoord> Cells { get; init; } = Array.Empty<GridCoord>();
    public int TotalCost { get; init; }
}

public sealed class ReachabilityMap
{
    private readonly Dictionary<GridCoord, int> _costs;
    private readonly Dictionary<GridCoord, GridCoord> _previous;

    internal ReachabilityMap(
        Dictionary<GridCoord, int> costs,
        Dictionary<GridCoord, GridCoord> previous)
    {
        _costs = costs;
        _previous = previous;
    }

    public IEnumerable<KeyValuePair<GridCoord, int>> Cells =>
        _costs.OrderBy(pair => pair.Key);

    public int? CostAt(GridCoord coord) => _costs.TryGetValue(coord, out var cost) ? cost : null;

    public TacticalPath? PathTo(GridCoord start, GridCoord goal)
    {
        if (!_costs.TryGetValue(goal, out var cost)) return null;
        return new TacticalPath { Cells = Reconstruct(_previous, start, goal), TotalCost = cost };
    }

    internal static List<GridCoord> Reconstruct(
        IReadOnlyDictionary<GridCoord, GridCoord> previous,
        GridCoord start,
        GridCoord goal)
    {
        var cells = new List<GridCoord> { goal };
        var current = goal;
        while (current != start)
        {
            if (!previous.TryGetValue(current, out current))
                throw new InvalidOperationException("Path predecessor chain is incomplete.");
            cells.Add(current);
        }
        cells.Reverse();
        return cells;
    }
}

/// Deterministic A* and action-point reachability service.
public sealed class TacticalPathfinder
{
    private readonly IMovementCostPolicy _movement;

    public TacticalPathfinder(IMovementCostPolicy? movement = null) =>
        _movement = movement ?? new DefaultMovementCostPolicy();

    public TacticalPath? FindPath(
        TacticalBoard board,
        GridCoord start,
        GridCoord goal,
        string? actorId = null)
    {
        if (!board.TryGetCell(start, out _) || !board.TryGetCell(goal, out _)) return null;
        var costs = new Dictionary<GridCoord, int> { [start] = 0 };
        var previous = new Dictionary<GridCoord, GridCoord>();
        var frontier = new PriorityQueue<(GridCoord Coord, int Cost), (int Total, int Cost, int Level, int Y, int X)>();
        frontier.Enqueue((start, 0), (start.ManhattanDistance(goal), 0, start.Level, start.Y, start.X));
        while (frontier.TryDequeue(out var node, out _))
        {
            if (!costs.TryGetValue(node.Coord, out var known) || known != node.Cost) continue;
            if (node.Coord == goal)
                return new TacticalPath
                {
                    Cells = ReachabilityMap.Reconstruct(previous, start, goal),
                    TotalCost = known,
                };
            foreach (var neighbor in board.Neighbors(node.Coord))
            {
                var step = _movement.StepCost(board, node.Coord, neighbor, actorId);
                if (step is null) continue;
                var next = checked(known + step.Value);
                if (costs.TryGetValue(neighbor, out var current) && next >= current) continue;
                costs[neighbor] = next;
                previous[neighbor] = node.Coord;
                frontier.Enqueue(
                    (neighbor, next),
                    (next + neighbor.ManhattanDistance(goal), next, neighbor.Level, neighbor.Y, neighbor.X));
            }
        }
        return null;
    }

    public ReachabilityMap Reachable(
        TacticalBoard board,
        GridCoord start,
        int movementBudget,
        string? actorId = null)
    {
        var costs = new Dictionary<GridCoord, int>();
        var previous = new Dictionary<GridCoord, GridCoord>();
        if (!board.TryGetCell(start, out _) || movementBudget < 0)
            return new ReachabilityMap(costs, previous);
        costs[start] = 0;
        var frontier = new PriorityQueue<(GridCoord Coord, int Cost), (int Cost, int Level, int Y, int X)>();
        frontier.Enqueue((start, 0), (0, start.Level, start.Y, start.X));
        while (frontier.TryDequeue(out var node, out _))
        {
            if (costs[node.Coord] != node.Cost) continue;
            foreach (var neighbor in board.Neighbors(node.Coord))
            {
                var step = _movement.StepCost(board, node.Coord, neighbor, actorId);
                if (step is null) continue;
                var next = checked(node.Cost + step.Value);
                if (next > movementBudget ||
                    costs.TryGetValue(neighbor, out var current) && next >= current) continue;
                costs[neighbor] = next;
                previous[neighbor] = node.Coord;
                frontier.Enqueue((neighbor, next), (next, neighbor.Level, neighbor.Y, neighbor.X));
            }
        }
        return new ReachabilityMap(costs, previous);
    }
}

public interface ILineOfSightPolicy
{
    bool HasLineOfSight(TacticalBoard board, GridCoord origin, GridCoord target);
}

public sealed class GridLineOfSightPolicy : ILineOfSightPolicy
{
    public bool HasLineOfSight(TacticalBoard board, GridCoord origin, GridCoord target)
    {
        if (origin.Level != target.Level ||
            !board.TryGetCell(origin, out _) ||
            !board.TryGetCell(target, out _)) return false;
        foreach (var coord in RasterLine(origin, target).Skip(1))
        {
            if (coord == target) break;
            if (!board.TryGetCell(coord, out var cell) || cell.BlocksSight) return false;
        }
        return true;
    }

    private static IEnumerable<GridCoord> RasterLine(GridCoord start, GridCoord end)
    {
        var x = start.X;
        var y = start.Y;
        var dx = Math.Abs(end.X - start.X);
        var sx = start.X < end.X ? 1 : -1;
        var dy = -Math.Abs(end.Y - start.Y);
        var sy = start.Y < end.Y ? 1 : -1;
        var error = dx + dy;
        while (true)
        {
            yield return new GridCoord(x, y, start.Level);
            if (x == end.X && y == end.Y) yield break;
            var twice = error * 2;
            if (twice >= dy) { error += dy; x += sx; }
            if (twice <= dx) { error += dx; y += sy; }
        }
    }
}

public readonly record struct VisibilityEntry(int Faction, GridCoord Coord, VisibilityState State);

public sealed class VisibilityMap
{
    private readonly Dictionary<int, Dictionary<GridCoord, VisibilityState>> _factions = new();

    public VisibilityState StateAt(int faction, GridCoord coord) =>
        _factions.TryGetValue(faction, out var cells) &&
        cells.TryGetValue(coord, out var state) ? state : VisibilityState.Unseen;

    public void Update(
        int faction,
        TacticalBoard board,
        IEnumerable<(GridCoord Origin, int Range)> observers,
        ILineOfSightPolicy? lineOfSight = null)
    {
        lineOfSight ??= new GridLineOfSightPolicy();
        if (!_factions.TryGetValue(faction, out var cells))
            _factions[faction] = cells = new Dictionary<GridCoord, VisibilityState>();
        foreach (var coord in cells
                     .Where(pair => pair.Value == VisibilityState.Visible)
                     .Select(pair => pair.Key)
                     .ToArray())
            cells[coord] = VisibilityState.Explored;
        foreach (var (origin, range) in observers)
            foreach (var cell in board.Cells)
                if (origin.ManhattanDistance(cell.Coord) <= range &&
                    lineOfSight.HasLineOfSight(board, origin, cell.Coord))
                    cells[cell.Coord] = VisibilityState.Visible;
    }

    public List<VisibilityEntry> CreateSnapshot() =>
        _factions
            .SelectMany(faction => faction.Value.Select(cell =>
                new VisibilityEntry(faction.Key, cell.Key, cell.Value)))
            .OrderBy(entry => entry.Faction)
            .ThenBy(entry => entry.Coord)
            .ToList();

    public static VisibilityMap FromSnapshot(IEnumerable<VisibilityEntry> entries)
    {
        var result = new VisibilityMap();
        foreach (var entry in entries)
        {
            if (!result._factions.TryGetValue(entry.Faction, out var cells))
                result._factions[entry.Faction] = cells = new();
            cells[entry.Coord] = entry.State;
        }
        return result;
    }
}

public enum TurnPhase { NotStarted, Acting, Resolving, Reaction, Complete }

public sealed class TurnParticipant
{
    public string EntityId { get; init; } = "";
    public int Faction { get; init; }
    public int Initiative { get; init; }
    public int MaxActionPoints { get; init; } = 2;
    public int ActionPoints { get; internal set; } = 2;
    public bool Active { get; set; } = true;
}

public abstract record ActionTarget
{
    private ActionTarget() { }
    public sealed record None : ActionTarget;
    public sealed record Cell(GridCoord Coord) : ActionTarget;
    public sealed record Entity(string EntityId) : ActionTarget;
}

public sealed record TacticalAction(
    long Id,
    string ActorId,
    string Kind,
    int ActionPointCost,
    ActionTarget Target,
    IReadOnlyDictionary<string, string>? Payload = null);

public sealed record TurnParticipantSnapshot(
    string EntityId,
    int Faction,
    int Initiative,
    int MaxActionPoints,
    int ActionPoints,
    bool Active);

public sealed record TacticalActionSnapshot(
    long Id,
    string ActorId,
    string Kind,
    int ActionPointCost,
    string TargetKind,
    GridCoord? TargetCell,
    string? TargetEntityId,
    Dictionary<string, string> Payload);

public sealed class TurnDirectorSnapshot
{
    public List<TurnParticipantSnapshot> Participants { get; init; } = new();
    public List<string> Order { get; init; } = new();
    public int ActiveIndex { get; init; }
    public int Round { get; init; }
    public TurnPhase Phase { get; init; }
    public List<TacticalActionSnapshot> Actions { get; init; } = new();
    public List<TacticalActionSnapshot> Reactions { get; init; } = new();
}

public abstract record TacticalEvent
{
    private TacticalEvent() { }
    public sealed record EncounterStarted : TacticalEvent;
    public sealed record RoundStarted(int Round) : TacticalEvent;
    public sealed record TurnStarted(string ActorId) : TacticalEvent;
    public sealed record ActionQueued(long ActionId) : TacticalEvent;
    public sealed record ActionResolved(long ActionId) : TacticalEvent;
    public sealed record TurnEnded(string ActorId) : TacticalEvent;
    public sealed record EncounterCompleted : TacticalEvent;
}

public interface ITacticalCommand { }
public sealed record QueueActionCommand(TacticalAction Action, bool IsReaction = false) : ITacticalCommand;
public sealed record EndTurnCommand(string ActorId) : ITacticalCommand;

public interface ITacticalActionExecutor
{
    IEnumerable<TacticalEvent> Execute(TacticalAction action);
}

/// Command queue plus deterministic initiative coordinator.
public sealed class TurnDirector
{
    private readonly Dictionary<string, TurnParticipant> _participants = new(StringComparer.Ordinal);
    private readonly Queue<TacticalAction> _actions = new();
    private readonly Queue<TacticalAction> _reactions = new();
    private List<string> _order = new();
    private int _activeIndex;

    public int Round { get; private set; }
    public TurnPhase Phase { get; private set; }
    public string? ActiveActor => _activeIndex < _order.Count ? _order[_activeIndex] : null;
    public IEnumerable<TurnParticipant> Participants =>
        _participants.Values.OrderBy(participant => participant.EntityId, StringComparer.Ordinal);

    public void AddOrReplace(TurnParticipant participant) =>
        _participants[participant.EntityId] = participant;

    public IReadOnlyList<TacticalEvent> Start()
    {
        _order = _participants.Values
            .Where(participant => participant.Active)
            .OrderByDescending(participant => participant.Initiative)
            .ThenBy(participant => participant.EntityId, StringComparer.Ordinal)
            .Select(participant => participant.EntityId)
            .ToList();
        _activeIndex = 0;
        Round = 1;
        RefreshActionPoints();
        if (_order.Count == 0)
        {
            Phase = TurnPhase.Complete;
            return new TacticalEvent[] { new TacticalEvent.EncounterStarted(), new TacticalEvent.EncounterCompleted() };
        }
        Phase = TurnPhase.Acting;
        return new TacticalEvent[]
        {
            new TacticalEvent.EncounterStarted(),
            new TacticalEvent.RoundStarted(Round),
            new TacticalEvent.TurnStarted(ActiveActor!),
        };
    }

    public IReadOnlyList<TacticalEvent> Submit(ITacticalCommand command) => command switch
    {
        QueueActionCommand queue => Queue(queue.Action, queue.IsReaction),
        EndTurnCommand end => EndTurn(end.ActorId),
        _ => throw new ArgumentOutOfRangeException(nameof(command)),
    };

    public IReadOnlyList<TacticalEvent> ResolveNext(ITacticalActionExecutor executor)
    {
        TacticalAction? action = null;
        if (_reactions.TryDequeue(out var reaction))
        {
            action = reaction;
            Phase = TurnPhase.Reaction;
        }
        else if (_actions.TryDequeue(out var queued))
        {
            action = queued;
            Phase = TurnPhase.Resolving;
        }
        if (action is null)
        {
            Phase = TurnPhase.Acting;
            return Array.Empty<TacticalEvent>();
        }
        var events = executor.Execute(action).ToList();
        events.Add(new TacticalEvent.ActionResolved(action.Id));
        if (_reactions.Count == 0 && _actions.Count == 0) Phase = TurnPhase.Acting;
        return events;
    }

    public TurnDirectorSnapshot CreateSnapshot() => new()
    {
        Participants = Participants.Select(participant => new TurnParticipantSnapshot(
            participant.EntityId,
            participant.Faction,
            participant.Initiative,
            participant.MaxActionPoints,
            participant.ActionPoints,
            participant.Active)).ToList(),
        Order = _order.ToList(),
        ActiveIndex = _activeIndex,
        Round = Round,
        Phase = Phase,
        Actions = _actions.Select(ToSnapshot).ToList(),
        Reactions = _reactions.Select(ToSnapshot).ToList(),
    };

    public static TurnDirector FromSnapshot(TurnDirectorSnapshot snapshot)
    {
        var director = new TurnDirector
        {
            _order = snapshot.Order.ToList(),
            _activeIndex = snapshot.ActiveIndex,
            Round = snapshot.Round,
            Phase = snapshot.Phase,
        };
        foreach (var saved in snapshot.Participants)
            director.AddOrReplace(new TurnParticipant
            {
                EntityId = saved.EntityId,
                Faction = saved.Faction,
                Initiative = saved.Initiative,
                MaxActionPoints = saved.MaxActionPoints,
                ActionPoints = saved.ActionPoints,
                Active = saved.Active,
            });
        foreach (var action in snapshot.Actions) director._actions.Enqueue(FromSnapshot(action));
        foreach (var action in snapshot.Reactions) director._reactions.Enqueue(FromSnapshot(action));
        if (director._activeIndex < 0 || director._activeIndex >= Math.Max(1, director._order.Count))
            throw new JsonException("Turn snapshot active index is outside its initiative order.");
        if (director._order.Any(id => !director._participants.ContainsKey(id)))
            throw new JsonException("Turn snapshot initiative order references an unknown participant.");
        return director;
    }

    private IReadOnlyList<TacticalEvent> Queue(TacticalAction action, bool reaction)
    {
        if (!reaction && !StringComparer.Ordinal.Equals(ActiveActor, action.ActorId))
            throw new InvalidOperationException($"'{action.ActorId}' is not the active actor.");
        if (!_participants.TryGetValue(action.ActorId, out var participant))
            throw new KeyNotFoundException($"Participant '{action.ActorId}' does not exist.");
        if (participant.ActionPoints < action.ActionPointCost)
            throw new InvalidOperationException($"Participant '{action.ActorId}' has insufficient AP.");
        participant.ActionPoints -= action.ActionPointCost;
        (reaction ? _reactions : _actions).Enqueue(action);
        return new TacticalEvent[] { new TacticalEvent.ActionQueued(action.Id) };
    }

    private IReadOnlyList<TacticalEvent> EndTurn(string actorId)
    {
        if (!StringComparer.Ordinal.Equals(ActiveActor, actorId))
            throw new InvalidOperationException($"'{actorId}' is not the active actor.");
        var events = new List<TacticalEvent> { new TacticalEvent.TurnEnded(actorId) };
        _activeIndex++;
        if (_activeIndex >= _order.Count)
        {
            _activeIndex = 0;
            Round++;
            RefreshActionPoints();
            events.Add(new TacticalEvent.RoundStarted(Round));
        }
        events.Add(new TacticalEvent.TurnStarted(ActiveActor!));
        return events;
    }

    private void RefreshActionPoints()
    {
        foreach (var participant in _participants.Values)
            participant.ActionPoints = participant.MaxActionPoints;
    }

    private static TacticalActionSnapshot ToSnapshot(TacticalAction action)
    {
        var (kind, cell, entity) = action.Target switch
        {
            ActionTarget.Cell target => ("cell", (GridCoord?)target.Coord, (string?)null),
            ActionTarget.Entity target => ("entity", null, target.EntityId),
            _ => ("none", null, null),
        };
        return new TacticalActionSnapshot(
            action.Id,
            action.ActorId,
            action.Kind,
            action.ActionPointCost,
            kind,
            cell,
            entity,
            action.Payload?.ToDictionary(pair => pair.Key, pair => pair.Value, StringComparer.Ordinal)
                ?? new Dictionary<string, string>(StringComparer.Ordinal));
    }

    private static TacticalAction FromSnapshot(TacticalActionSnapshot action)
    {
        ActionTarget target = action.TargetKind switch
        {
            "cell" when action.TargetCell is { } cell => new ActionTarget.Cell(cell),
            "entity" when action.TargetEntityId is { } entity => new ActionTarget.Entity(entity),
            "none" => new ActionTarget.None(),
            _ => throw new JsonException($"Unknown or incomplete action target '{action.TargetKind}'."),
        };
        return new TacticalAction(
            action.Id,
            action.ActorId,
            action.Kind,
            action.ActionPointCost,
            target,
            action.Payload);
    }
}

public sealed class CombatStats
{
    public int MaxHealth { get; init; }
    public int Aim { get; init; }
    public int Defense { get; init; }
    public int Armor { get; init; }
    public int Mobility { get; init; }
    public int Will { get; init; }
}

public sealed class StatusEffect
{
    public string Key { get; init; } = "";
    public int RemainingRounds { get; set; }
    public int Stacks { get; set; } = 1;
}

public sealed class Combatant
{
    public string EntityId { get; init; } = "";
    public CombatStats Stats { get; init; } = new();
    public int Health { get; set; }
    public Dictionary<string, StatusEffect> Statuses { get; init; } = new(StringComparer.Ordinal);
    public Dictionary<string, int> Cooldowns { get; init; } = new(StringComparer.Ordinal);
    [JsonIgnore] public bool IsAlive => Health > 0;

    public static Combatant Create(string entityId, CombatStats stats) => new()
    {
        EntityId = entityId,
        Stats = stats,
        Health = stats.MaxHealth,
    };

    public void TickRound()
    {
        foreach (var key in Cooldowns.Keys.ToArray())
            if (--Cooldowns[key] <= 0) Cooldowns.Remove(key);
        foreach (var (key, status) in Statuses.ToArray())
            if (--status.RemainingRounds <= 0) Statuses.Remove(key);
    }
}

public readonly record struct WeaponProfile(
    int BaseDamage,
    int ArmorPiercing,
    int Range,
    int Accuracy,
    int CriticalChanceBasisPoints,
    int CriticalBonusDamage);

public readonly record struct AttackContext(int Distance, CoverKind TargetCover, int ElevationDelta);

public readonly record struct CombatOutcome(
    bool Hit,
    bool Critical,
    int HitChanceBasisPoints,
    int Roll,
    int Damage,
    int TargetHealth,
    bool TargetKilled);

public interface IHitChancePolicy
{
    int GetHitChanceBasisPoints(
        Combatant attacker,
        Combatant target,
        WeaponProfile weapon,
        AttackContext context);
}

public sealed class DefaultHitChancePolicy : IHitChancePolicy
{
    public int GetHitChanceBasisPoints(
        Combatant attacker,
        Combatant target,
        WeaponProfile weapon,
        AttackContext context)
    {
        var rangePenalty = Math.Max(0, context.Distance - weapon.Range) * 5;
        var coverPenalty = context.TargetCover switch
        {
            CoverKind.Half => 20,
            CoverKind.Full => 40,
            _ => 0,
        };
        var elevationBonus = Math.Clamp(context.ElevationDelta, -2, 2) * 10;
        var percent = 65 + attacker.Stats.Aim + weapon.Accuracy - target.Stats.Defense
                      - coverPenalty - rangePenalty + elevationBonus;
        return Math.Clamp(percent, 0, 100) * 100;
    }
}

// Compatibility wrapper retained for projects compiled against Script API 0.10.
public sealed class DeterministicRandom : Engine.Gameplay.DeterministicRandom
{
    public DeterministicRandom(ulong seed) : base(seed) { }
}

public sealed class CombatResolver
{
    private readonly IHitChancePolicy _hitChance;

    public CombatResolver(IHitChancePolicy? hitChance = null) =>
        _hitChance = hitChance ?? new DefaultHitChancePolicy();

    public CombatOutcome ResolveAttack(
        Combatant attacker,
        Combatant target,
        WeaponProfile weapon,
        AttackContext context,
        DeterministicRandom random)
    {
        var chance = _hitChance.GetHitChanceBasisPoints(attacker, target, weapon, context);
        var roll = random.RollBasisPoints();
        var hit = roll < chance;
        var critical = hit && random.RollBasisPoints() < weapon.CriticalChanceBasisPoints;
        var rawDamage = hit
            ? weapon.BaseDamage + (critical ? weapon.CriticalBonusDamage : 0)
            : 0;
        var armor = Math.Max(0, target.Stats.Armor - weapon.ArmorPiercing);
        var damage = hit ? Math.Max(1, rawDamage - armor) : 0;
        target.Health = Math.Max(0, target.Health - damage);
        return new CombatOutcome(
            hit, critical, chance, roll, damage, target.Health, !target.IsAlive);
    }
}

public sealed class UtilityOption
{
    public string Key { get; init; } = "";
    public string ActorId { get; init; } = "";
    public string? TargetEntityId { get; init; }
    public GridCoord? TargetCell { get; init; }
    public float BaseScore { get; init; } = 1f;
    public Dictionary<string, float> Facts { get; init; } = new(StringComparer.Ordinal);
}

public interface IUtilityConsideration
{
    string Key { get; }
    float Evaluate(UtilityOption option);
}

public sealed record ScoredUtilityOption(
    UtilityOption Option,
    float Score,
    IReadOnlyDictionary<string, float> Considerations);

public sealed class UtilityBrain
{
    private readonly List<IUtilityConsideration> _considerations = new();

    public UtilityBrain Add(IUtilityConsideration consideration)
    {
        _considerations.Add(consideration);
        return this;
    }

    public ScoredUtilityOption Score(UtilityOption option)
    {
        var score = option.BaseScore;
        var values = new SortedDictionary<string, float>(StringComparer.Ordinal);
        foreach (var consideration in _considerations)
        {
            var value = Math.Clamp(consideration.Evaluate(option), 0f, 1f);
            values[consideration.Key] = value;
            score *= value;
        }
        return new ScoredUtilityOption(option, score, values);
    }

    public ScoredUtilityOption? Choose(IEnumerable<UtilityOption> options) =>
        options.Select(Score)
            .OrderByDescending(option => option.Score)
            .ThenBy(option => option.Option.Key, StringComparer.Ordinal)
            .FirstOrDefault();
}

public sealed class FactCurve : IUtilityConsideration
{
    public string Key { get; init; } = "";
    public string Fact { get; init; } = "";
    public float InputMin { get; init; }
    public float InputMax { get; init; } = 1f;
    public bool Invert { get; init; }

    public float Evaluate(UtilityOption option)
    {
        option.Facts.TryGetValue(Fact, out var value);
        var range = InputMax - InputMin;
        var normalized = Math.Abs(range) <= float.Epsilon
            ? 0f
            : Math.Clamp((value - InputMin) / range, 0f, 1f);
        return Invert ? 1f - normalized : normalized;
    }
}

public sealed class TacticalSessionSnapshot
{
    public TacticalBoardSnapshot Board { get; init; } = new();
    public TurnDirectorSnapshot Turns { get; init; } = new();
    public List<VisibilityEntry> Visibility { get; init; } = new();
    public List<Combatant> Combatants { get; init; } = new();
    public ulong RandomState { get; init; }
}

/// Save-friendly façade for project-owned tactical state.
public sealed class TacticalSession
{
    public TacticalBoard Board { get; private set; } = new();
    public TurnDirector Turns { get; private set; } = new();
    public VisibilityMap Visibility { get; private set; } = new();
    public Dictionary<string, Combatant> Combatants { get; private set; } = new(StringComparer.Ordinal);
    public DeterministicRandom Random { get; private set; }

    public TacticalSession(ulong seed = 0) => Random = new DeterministicRandom(seed);

    public string ToJson(JsonSerializerOptions? options = null) =>
        JsonSerializer.Serialize(new TacticalSessionSnapshot
        {
            Board = Board.CreateSnapshot(),
            Turns = Turns.CreateSnapshot(),
            Visibility = Visibility.CreateSnapshot(),
            Combatants = Combatants.Values.OrderBy(unit => unit.EntityId, StringComparer.Ordinal).ToList(),
            RandomState = Random.State,
        }, options);

    public static TacticalSession FromJson(string json, JsonSerializerOptions? options = null)
    {
        var snapshot = JsonSerializer.Deserialize<TacticalSessionSnapshot>(json, options)
                       ?? throw new JsonException("Tactical session payload is empty.");
        return new TacticalSession(snapshot.RandomState)
        {
            Board = TacticalBoard.FromSnapshot(snapshot.Board),
            Turns = TurnDirector.FromSnapshot(snapshot.Turns),
            Visibility = VisibilityMap.FromSnapshot(snapshot.Visibility),
            Combatants = snapshot.Combatants.ToDictionary(
                unit => unit.EntityId, unit => unit, StringComparer.Ordinal),
        };
    }
}
