// <auto-generated>
// Engine-owned multiplayer and OpenXR gameplay bridge.
// </auto-generated>
#nullable enable
using System.Numerics;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Engine;

public readonly record struct NetworkRequest(uint RequestId);

public sealed record NetworkOperationResult(
    uint RequestId,
    string Operation,
    bool Success,
    string? Value,
    string? Error);

public sealed record NetworkPeer(ulong PeerId, string DisplayName, double LastSeenSeconds);
public sealed record NetworkOwnership(ulong NetworkEntityId, ulong? OwnerPeerId, ulong Revision);
public sealed record ReplicatedState(
    ulong NetworkEntityId,
    string Component,
    ulong Revision,
    byte[] Payload);

public readonly record struct NetworkRpcTarget(string Kind, ulong? Id = null)
{
    public static NetworkRpcTarget Server => new("server");
    public static NetworkRpcTarget All => new("all");
    public static NetworkRpcTarget Others => new("others");
    public static NetworkRpcTarget Peer(ulong peerId) => new("peer", peerId);
    public static NetworkRpcTarget Owner(ulong networkEntityId) => new("owner", networkEntityId);

    internal RpcTargetState ToState()
    {
        if (Kind is not ("server" or "all" or "others" or "peer" or "owner"))
            throw new ArgumentException("Unknown RPC target kind.", nameof(Kind));
        if (Kind is "peer" or "owner" && Id is null)
            throw new ArgumentException("Peer and owner RPC targets require an id.", nameof(Id));
        return new RpcTargetState { Kind = Kind, Id = Id };
    }
}

public sealed record NetworkRpcEvent(
    ulong RpcId,
    ulong SenderPeerId,
    NetworkRpcTarget Target,
    string Method,
    bool Reliable,
    byte[] Payload);

public sealed record NetworkLobby(
    string Id,
    ulong OwnerPeerId,
    string Name,
    ushort MaxMembers,
    IReadOnlyList<ulong> Members,
    bool Joinable,
    IReadOnlyDictionary<string, string> Metadata);

public sealed record NetworkFriend(
    ulong PeerId,
    string DisplayName,
    bool Online,
    string? LobbyId);

public sealed class NetworkLobbyOptions
{
    public required string Id { get; init; }
    public required string Name { get; init; }
    public ushort MaxMembers { get; init; } = 8;
    public bool Joinable { get; init; } = true;
    public IReadOnlyDictionary<string, string> Metadata { get; init; } =
        new Dictionary<string, string>(StringComparer.Ordinal);
}

/// Engine-owned multiplayer bridge. Calls are deferred to the frame boundary;
/// their results and all received RPCs appear in the next frame snapshot.
public sealed class ScriptNetwork
{
    private const int MaxPayloadBytes = 48 * 1024;
    private readonly List<GameplayCommandState> _pending = new();
    private Dictionary<uint, NetworkOperationResult> _results = new();

    public bool Active { get; private set; }
    public string? Role { get; private set; }
    public ulong? LocalPeerId { get; private set; }
    public ulong? SessionId { get; private set; }
    public IReadOnlyList<NetworkPeer> Peers { get; private set; } = Array.Empty<NetworkPeer>();
    public IReadOnlyList<NetworkOwnership> Ownership { get; private set; } =
        Array.Empty<NetworkOwnership>();
    public IReadOnlyList<ReplicatedState> ReplicatedStates { get; private set; } =
        Array.Empty<ReplicatedState>();
    public IReadOnlyList<NetworkRpcEvent> RpcEvents { get; private set; } =
        Array.Empty<NetworkRpcEvent>();
    public IReadOnlyList<NetworkLobby> Lobbies { get; private set; } = Array.Empty<NetworkLobby>();
    public IReadOnlyList<NetworkFriend> Friends { get; private set; } = Array.Empty<NetworkFriend>();
    public IReadOnlyCollection<NetworkOperationResult> OperationResults => _results.Values;

    public NetworkRequest Host(
        ulong sessionId,
        string bindAddress = "0.0.0.0:0",
        bool listenServer = true) =>
        Enqueue(NetworkCommandState.Host(bindAddress, sessionId, listenServer));

    public NetworkRequest Connect(
        string serverAddress,
        string displayName,
        string bindAddress = "0.0.0.0:0") =>
        Enqueue(NetworkCommandState.Connect(bindAddress, serverAddress, displayName));

    public NetworkRequest Disconnect() => Enqueue(NetworkCommandState.Disconnect());

    public NetworkRequest AssignOwner(ulong networkEntityId, ulong? ownerPeerId) =>
        Enqueue(NetworkCommandState.AssignOwner(networkEntityId, ownerPeerId));

    public NetworkRequest WriteReplicatedState(
        ulong networkEntityId,
        string component,
        ReadOnlySpan<byte> payload) =>
        Enqueue(NetworkCommandState.WriteComponent(
            networkEntityId, component, EncodePayload(payload)));

    public NetworkRequest SendRpc(
        NetworkRpcTarget target,
        string method,
        ReadOnlySpan<byte> payload,
        bool reliable = true) =>
        Enqueue(NetworkCommandState.SendRpc(
            target.ToState(), method, reliable, EncodePayload(payload)));

    public NetworkRequest CreateLobby(NetworkLobbyOptions options)
    {
        ArgumentNullException.ThrowIfNull(options);
        return Enqueue(NetworkCommandState.CreateLobby(options));
    }

    public NetworkRequest JoinLobby(string lobbyId) =>
        Enqueue(NetworkCommandState.Lobby("join_lobby", lobbyId));

    public NetworkRequest LeaveLobby(string lobbyId) =>
        Enqueue(NetworkCommandState.Lobby("leave_lobby", lobbyId));

    public NetworkRequest RemoveLobby(string lobbyId) =>
        Enqueue(NetworkCommandState.Lobby("remove_lobby", lobbyId));

    public NetworkRequest UpdateFriend(NetworkFriend friend)
    {
        ArgumentNullException.ThrowIfNull(friend);
        return Enqueue(NetworkCommandState.UpdateFriend(friend));
    }

    public NetworkRequest RemoveFriend(ulong peerId) =>
        Enqueue(NetworkCommandState.RemoveFriend(peerId));

    public bool TryGetResult(NetworkRequest request, out NetworkOperationResult result) =>
        _results.TryGetValue(request.RequestId, out result!);

    public bool TryGetReplicatedState(
        ulong networkEntityId,
        string component,
        out ReplicatedState state)
    {
        state = ReplicatedStates.FirstOrDefault(candidate =>
            candidate.NetworkEntityId == networkEntityId &&
            string.Equals(candidate.Component, component, StringComparison.Ordinal))!;
        return state is not null;
    }

    internal void Replace(NetworkSnapshotState state)
    {
        state ??= new NetworkSnapshotState();
        Active = state.Active;
        Role = state.Role;
        LocalPeerId = state.LocalPeerId;
        SessionId = state.SessionId;
        Peers = state.Peers.Select(peer =>
            new NetworkPeer(peer.PeerId, peer.DisplayName, peer.LastSeenSeconds)).ToArray();
        Ownership = state.Ownership.Select(item =>
            new NetworkOwnership(item.NetworkEntityId, item.OwnerPeerId, item.Revision)).ToArray();
        ReplicatedStates = state.ReplicatedStates.Select(item =>
            new ReplicatedState(item.NetworkEntityId, item.Component, item.Revision,
                DecodePayload(item.Payload))).ToArray();
        RpcEvents = state.RpcEvents.Select(item =>
            new NetworkRpcEvent(item.RpcId, item.SenderPeerId,
                new NetworkRpcTarget(item.Target.Kind, item.Target.Id), item.Method,
                item.Reliable, DecodePayload(item.Payload))).ToArray();
        Lobbies = state.Lobbies.Select(item =>
            new NetworkLobby(item.Id, item.OwnerPeerId, item.Name, item.MaxMembers,
                item.Members, item.Joinable,
                new Dictionary<string, string>(item.Metadata, StringComparer.Ordinal))).ToArray();
        Friends = state.Friends.Select(item =>
            new NetworkFriend(item.PeerId, item.DisplayName, item.Online, item.LobbyId)).ToArray();
        _results = state.OperationResults.ToDictionary(
            item => item.RequestId,
            item => new NetworkOperationResult(item.RequestId, item.Operation,
                item.Success, item.Value, item.Error));
    }

    internal void DrainTo(List<GameplayCommandState> commands)
    {
        commands.AddRange(_pending);
        _pending.Clear();
    }

    private NetworkRequest Enqueue(NetworkCommandState command)
    {
        command.Validate();
        var request = new NetworkRequest(OnlineRequestIds.Next());
        _pending.Add(GameplayCommandState.Network(request.RequestId, command));
        return request;
    }

    private static int[] EncodePayload(ReadOnlySpan<byte> payload)
    {
        if (payload.Length > MaxPayloadBytes)
            throw new ArgumentException($"Network payloads are limited to {MaxPayloadBytes} bytes.",
                nameof(payload));
        var encoded = new int[payload.Length];
        for (var index = 0; index < payload.Length; index++)
            encoded[index] = payload[index];
        return encoded;
    }

    private static byte[] DecodePayload(IReadOnlyList<int> payload)
    {
        var decoded = new byte[payload.Count];
        for (var index = 0; index < payload.Count; index++)
        {
            if ((uint)payload[index] > byte.MaxValue)
                throw new InvalidOperationException("Engine sent an invalid network payload byte.");
            decoded[index] = (byte)payload[index];
        }
        return decoded;
    }
}

public readonly record struct XrPoseSnapshot(
    Quaternion Orientation,
    Vector3 Position,
    bool OrientationValid,
    bool PositionValid,
    bool Tracked);

public readonly record struct XrFieldOfView(
    float AngleLeft,
    float AngleRight,
    float AngleUp,
    float AngleDown);

public readonly record struct XrViewSnapshot(XrPoseSnapshot Pose, XrFieldOfView FieldOfView);

public sealed record XrFrameSnapshot(
    long PredictedDisplayTimeNanoseconds,
    bool ShouldRender,
    IReadOnlyList<XrViewSnapshot> Views,
    XrPoseSnapshot Head,
    XrPoseSnapshot LeftHand,
    XrPoseSnapshot RightHand);

/// Read-only gameplay view of the OpenXR frame owned by the native renderer.
public sealed class ScriptXR
{
    private Dictionary<string, XrActionValueState> _actions =
        new(StringComparer.Ordinal);

    public bool Active { get; private set; }
    public XrFrameSnapshot? Frame { get; private set; }

    public bool TryGetBoolean(string action, out bool value)
    {
        value = false;
        if (!_actions.TryGetValue(action, out var state) || state.Type != "boolean" ||
            state.Value.ValueKind is not (JsonValueKind.True or JsonValueKind.False))
            return false;
        value = state.Value.GetBoolean();
        return true;
    }

    public bool TryGetFloat(string action, out float value)
    {
        value = 0f;
        return _actions.TryGetValue(action, out var state) &&
            state.Type == "float" && state.Value.TryGetSingle(out value);
    }

    public bool TryGetVector2(string action, out Vector2 value)
    {
        value = default;
        if (!_actions.TryGetValue(action, out var state) || state.Type != "vector2" ||
            state.Value.ValueKind != JsonValueKind.Array || state.Value.GetArrayLength() != 2)
            return false;
        value = new Vector2(state.Value[0].GetSingle(), state.Value[1].GetSingle());
        return true;
    }

    public bool TryGetPose(string action, out XrPoseSnapshot value)
    {
        value = default;
        if (!_actions.TryGetValue(action, out var state) || state.Type != "pose")
            return false;
        var pose = state.Value.Deserialize<XrPoseState>();
        if (pose is null)
            return false;
        value = pose.ToPublic();
        return true;
    }

    internal void Replace(XrSnapshotState state)
    {
        state ??= new XrSnapshotState();
        Active = state.Active;
        Frame = state.Frame?.ToPublic();
        _actions = new Dictionary<string, XrActionValueState>(state.Actions, StringComparer.Ordinal);
    }
}

internal static class OnlineRequestIds
{
    private static int _next;
    public static uint Next() => unchecked((uint)Interlocked.Increment(ref _next));
}

internal sealed class NetworkSnapshotState
{
    [JsonPropertyName("active")] public bool Active { get; set; }
    [JsonPropertyName("role")] public string? Role { get; set; }
    [JsonPropertyName("local_peer_id")] public ulong? LocalPeerId { get; set; }
    [JsonPropertyName("session_id")] public ulong? SessionId { get; set; }
    [JsonPropertyName("peers")] public List<NetworkPeerState> Peers { get; set; } = new();
    [JsonPropertyName("ownership")] public List<NetworkOwnershipState> Ownership { get; set; } = new();
    [JsonPropertyName("replicated_states")] public List<ReplicatedStateState> ReplicatedStates { get; set; } = new();
    [JsonPropertyName("rpc_events")] public List<RpcEventState> RpcEvents { get; set; } = new();
    [JsonPropertyName("lobbies")] public List<LobbyState> Lobbies { get; set; } = new();
    [JsonPropertyName("friends")] public List<FriendState> Friends { get; set; } = new();
    [JsonPropertyName("operation_results")] public List<NetworkOperationResultState> OperationResults { get; set; } = new();
}

internal sealed class NetworkPeerState
{
    [JsonPropertyName("peer_id")] public ulong PeerId { get; set; }
    [JsonPropertyName("display_name")] public string DisplayName { get; set; } = "";
    [JsonPropertyName("last_seen_seconds")] public double LastSeenSeconds { get; set; }
}

internal sealed class NetworkOwnershipState
{
    [JsonPropertyName("network_entity_id")] public ulong NetworkEntityId { get; set; }
    [JsonPropertyName("owner_peer_id")] public ulong? OwnerPeerId { get; set; }
    [JsonPropertyName("revision")] public ulong Revision { get; set; }
}

internal sealed class ReplicatedStateState
{
    [JsonPropertyName("network_entity_id")] public ulong NetworkEntityId { get; set; }
    [JsonPropertyName("component")] public string Component { get; set; } = "";
    [JsonPropertyName("revision")] public ulong Revision { get; set; }
    [JsonPropertyName("payload")] public int[] Payload { get; set; } = Array.Empty<int>();
}

internal sealed class RpcTargetState
{
    [JsonPropertyName("kind")] public required string Kind { get; init; }
    [JsonPropertyName("id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public ulong? Id { get; init; }
}

internal sealed class RpcEventState
{
    [JsonPropertyName("rpc_id")] public ulong RpcId { get; set; }
    [JsonPropertyName("sender_peer_id")] public ulong SenderPeerId { get; set; }
    [JsonPropertyName("target")] public RpcTargetState Target { get; set; } = new() { Kind = "server" };
    [JsonPropertyName("method")] public string Method { get; set; } = "";
    [JsonPropertyName("reliable")] public bool Reliable { get; set; }
    [JsonPropertyName("payload")] public int[] Payload { get; set; } = Array.Empty<int>();
}

internal sealed class LobbyState
{
    [JsonPropertyName("id")] public string Id { get; set; } = "";
    [JsonPropertyName("owner_peer_id")] public ulong OwnerPeerId { get; set; }
    [JsonPropertyName("name")] public string Name { get; set; } = "";
    [JsonPropertyName("max_members")] public ushort MaxMembers { get; set; }
    [JsonPropertyName("members")] public ulong[] Members { get; set; } = Array.Empty<ulong>();
    [JsonPropertyName("joinable")] public bool Joinable { get; set; }
    [JsonPropertyName("metadata")] public Dictionary<string, string> Metadata { get; set; } = new();
}

internal sealed class FriendState
{
    [JsonPropertyName("peer_id")] public ulong PeerId { get; set; }
    [JsonPropertyName("display_name")] public string DisplayName { get; set; } = "";
    [JsonPropertyName("online")] public bool Online { get; set; }
    [JsonPropertyName("lobby_id")] public string? LobbyId { get; set; }
}

internal sealed class NetworkOperationResultState
{
    [JsonPropertyName("request_id")] public uint RequestId { get; set; }
    [JsonPropertyName("operation")] public string Operation { get; set; } = "";
    [JsonPropertyName("success")] public bool Success { get; set; }
    [JsonPropertyName("value")] public string? Value { get; set; }
    [JsonPropertyName("error")] public string? Error { get; set; }
}

internal sealed class NetworkCommandState
{
    [JsonPropertyName("kind")] public required string Kind { get; init; }
    [JsonPropertyName("bind_address")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] public string? BindAddress { get; init; }
    [JsonPropertyName("server_address")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] public string? ServerAddress { get; init; }
    [JsonPropertyName("display_name")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] public string? DisplayName { get; init; }
    [JsonPropertyName("session_id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] public ulong? SessionId { get; init; }
    [JsonPropertyName("listen_server")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] public bool? ListenServer { get; init; }
    [JsonPropertyName("network_entity_id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] public ulong? NetworkEntityId { get; init; }
    [JsonPropertyName("owner_peer_id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] public ulong? OwnerPeerId { get; init; }
    [JsonPropertyName("component")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] public string? Component { get; init; }
    [JsonPropertyName("payload")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] public int[]? Payload { get; init; }
    [JsonPropertyName("target")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] public RpcTargetState? Target { get; init; }
    [JsonPropertyName("method")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] public string? Method { get; init; }
    [JsonPropertyName("reliable")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] public bool? Reliable { get; init; }
    [JsonPropertyName("lobby_id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] public string? LobbyId { get; init; }
    [JsonPropertyName("name")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] public string? Name { get; init; }
    [JsonPropertyName("max_members")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] public ushort? MaxMembers { get; init; }
    [JsonPropertyName("joinable")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] public bool? Joinable { get; init; }
    [JsonPropertyName("metadata")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] public Dictionary<string, string>? Metadata { get; init; }
    [JsonPropertyName("friend")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] public FriendState? Friend { get; init; }
    [JsonPropertyName("peer_id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] public ulong? PeerId { get; init; }

    public static NetworkCommandState Host(string bind, ulong sessionId, bool listen) =>
        new() { Kind = "host", BindAddress = bind, SessionId = sessionId, ListenServer = listen };
    public static NetworkCommandState Connect(string bind, string server, string name) =>
        new() { Kind = "connect", BindAddress = bind, ServerAddress = server, DisplayName = name };
    public static NetworkCommandState Disconnect() => new() { Kind = "disconnect" };
    public static NetworkCommandState AssignOwner(ulong entity, ulong? owner) =>
        new() { Kind = "assign_owner", NetworkEntityId = entity, OwnerPeerId = owner };
    public static NetworkCommandState WriteComponent(ulong entity, string component, int[] payload) =>
        new() { Kind = "write_component", NetworkEntityId = entity, Component = component, Payload = payload };
    public static NetworkCommandState SendRpc(RpcTargetState target, string method, bool reliable, int[] payload) =>
        new() { Kind = "send_rpc", Target = target, Method = method, Reliable = reliable, Payload = payload };
    public static NetworkCommandState CreateLobby(NetworkLobbyOptions options) => new()
    {
        Kind = "create_lobby", LobbyId = options.Id, Name = options.Name,
        MaxMembers = options.MaxMembers, Joinable = options.Joinable,
        Metadata = new Dictionary<string, string>(options.Metadata, StringComparer.Ordinal)
    };
    public static NetworkCommandState Lobby(string kind, string lobbyId) =>
        new() { Kind = kind, LobbyId = lobbyId };
    public static NetworkCommandState UpdateFriend(NetworkFriend friend) => new()
    {
        Kind = "update_friend",
        Friend = new FriendState
        {
            PeerId = friend.PeerId, DisplayName = friend.DisplayName,
            Online = friend.Online, LobbyId = friend.LobbyId
        }
    };
    public static NetworkCommandState RemoveFriend(ulong peerId) =>
        new() { Kind = "remove_friend", PeerId = peerId };

    public void Validate()
    {
        static void Text(string? value, string name, int max)
        {
            if (string.IsNullOrEmpty(value) || value.Length > max || value.Any(char.IsControl))
                throw new ArgumentException($"{name} must contain 1 to {max} characters and no controls.");
        }
        switch (Kind)
        {
            case "host": Text(BindAddress, "Bind address", 256); break;
            case "connect":
                Text(BindAddress, "Bind address", 256);
                Text(ServerAddress, "Server address", 256);
                Text(DisplayName, "Display name", 128);
                break;
            case "write_component": Text(Component, "Replication component", 128); break;
            case "send_rpc": Text(Method, "RPC method", 128); break;
            case "create_lobby":
                Text(LobbyId, "Lobby id", 128); Text(Name, "Lobby name", 128);
                if (MaxMembers is null or 0) throw new ArgumentException("Lobby capacity must be positive.");
                break;
            case "join_lobby" or "leave_lobby" or "remove_lobby":
                Text(LobbyId, "Lobby id", 128); break;
        }
    }
}

internal sealed class XrSnapshotState
{
    [JsonPropertyName("active")] public bool Active { get; set; }
    [JsonPropertyName("frame")] public XrFrameState? Frame { get; set; }
    [JsonPropertyName("actions")] public Dictionary<string, XrActionValueState> Actions { get; set; } = new();
}

internal sealed class XrFrameState
{
    [JsonPropertyName("predicted_display_time_nanoseconds")] public long PredictedDisplayTimeNanoseconds { get; set; }
    [JsonPropertyName("should_render")] public bool ShouldRender { get; set; }
    [JsonPropertyName("views")] public XrViewState[] Views { get; set; } = new[] { new XrViewState(), new XrViewState() };
    [JsonPropertyName("head")] public XrPoseState Head { get; set; } = new();
    [JsonPropertyName("left_hand")] public XrPoseState LeftHand { get; set; } = new();
    [JsonPropertyName("right_hand")] public XrPoseState RightHand { get; set; } = new();

    public XrFrameSnapshot ToPublic() => new(
        PredictedDisplayTimeNanoseconds, ShouldRender,
        Views.Select(view => view.ToPublic()).ToArray(),
        Head.ToPublic(), LeftHand.ToPublic(), RightHand.ToPublic());
}

internal sealed class XrPoseState
{
    [JsonPropertyName("orientation")] public float[] Orientation { get; set; } = new float[] { 0, 0, 0, 1 };
    [JsonPropertyName("position")] public float[] Position { get; set; } = new float[3];
    [JsonPropertyName("orientation_valid")] public bool OrientationValid { get; set; }
    [JsonPropertyName("position_valid")] public bool PositionValid { get; set; }
    [JsonPropertyName("tracked")] public bool Tracked { get; set; }

    public XrPoseSnapshot ToPublic() => new(
        new Quaternion(Orientation[0], Orientation[1], Orientation[2], Orientation[3]),
        new Vector3(Position[0], Position[1], Position[2]),
        OrientationValid, PositionValid, Tracked);
}

internal sealed class XrFieldOfViewState
{
    [JsonPropertyName("angle_left")] public float AngleLeft { get; set; }
    [JsonPropertyName("angle_right")] public float AngleRight { get; set; }
    [JsonPropertyName("angle_up")] public float AngleUp { get; set; }
    [JsonPropertyName("angle_down")] public float AngleDown { get; set; }
}

internal sealed class XrViewState
{
    [JsonPropertyName("pose")] public XrPoseState Pose { get; set; } = new();
    [JsonPropertyName("fov")] public XrFieldOfViewState FieldOfView { get; set; } = new();
    public XrViewSnapshot ToPublic() => new(Pose.ToPublic(), new XrFieldOfView(
        FieldOfView.AngleLeft, FieldOfView.AngleRight,
        FieldOfView.AngleUp, FieldOfView.AngleDown));
}

internal sealed class XrActionValueState
{
    [JsonPropertyName("type")] public string Type { get; set; } = "";
    [JsonPropertyName("value")] public JsonElement Value { get; set; }
}

internal sealed partial class GameplayContextState
{
    [JsonPropertyName("network")] public NetworkSnapshotState Network { get; set; } = new();
    [JsonPropertyName("xr")] public XrSnapshotState Xr { get; set; } = new();
}

internal sealed partial class GameplayCommandState
{
    [JsonPropertyName("network")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public NetworkCommandState? NetworkCommand { get; init; }

    public static GameplayCommandState Network(uint requestId, NetworkCommandState network) => new()
    {
        Type = "network", RequestId = requestId, NetworkCommand = network
    };
}

public abstract partial class EngineBehaviour
{
    public ScriptNetwork Network { get; } = new();
    public ScriptXR XR { get; } = new();
}
