// <auto-generated>
// Engine-owned rendering/VFX helpers compiled into EngineGameplay.dll.
// </auto-generated>
#nullable enable
using Engine;

namespace Engine.Rendering;

public sealed record LodLevelSettings(
    float Distance,
    string MeshAsset,
    string? MaterialAsset = null);

public sealed class LodGroupSettings
{
    public float MinimumDistance { get; init; }
    public float CullDistance { get; init; }
    public IReadOnlyList<LodLevelSettings> Levels { get; init; } =
        Array.Empty<LodLevelSettings>();

    internal void Validate()
    {
        RenderingScriptTools.FiniteNonNegative(MinimumDistance, nameof(MinimumDistance));
        RenderingScriptTools.FiniteNonNegative(CullDistance, nameof(CullDistance));
        if (CullDistance > 0.0f && CullDistance <= MinimumDistance)
            throw new ArgumentException(
                "CullDistance must be zero or greater than MinimumDistance.");
        var previous = 0.0f;
        foreach (var level in Levels)
        {
            RenderingScriptTools.FiniteNonNegative(level.Distance, nameof(level.Distance));
            if (level.Distance <= previous || level.Distance < MinimumDistance ||
                (CullDistance > 0.0f && level.Distance >= CullDistance))
                throw new ArgumentException(
                    "LOD level distances must be strictly increasing inside the group range.");
            RenderingScriptTools.AssetId(level.MeshAsset, nameof(level.MeshAsset));
            if (level.MaterialAsset != null)
                RenderingScriptTools.AssetId(level.MaterialAsset, nameof(level.MaterialAsset));
            previous = level.Distance;
        }
    }
}

public enum HlodRole
{
    Source,
    Proxy
}

public sealed class HlodClusterSettings
{
    public required string ClusterId { get; init; }
    public HlodRole Role { get; init; }
    public float ActivationDistance { get; init; }
    public float CullDistance { get; init; }

    internal void Validate()
    {
        RenderingScriptTools.AssetId(ClusterId, nameof(ClusterId));
        RenderingScriptTools.FiniteNonNegative(
            ActivationDistance, nameof(ActivationDistance));
        RenderingScriptTools.FiniteNonNegative(CullDistance, nameof(CullDistance));
        if (Role == HlodRole.Proxy && CullDistance > 0.0f &&
            CullDistance <= ActivationDistance)
            throw new ArgumentException(
                "Proxy CullDistance must be zero or greater than ActivationDistance.");
    }
}

public enum ParticleSimulationMode
{
    Cpu,
    Gpu
}

public sealed class ParticleEmitterSettings
{
    public bool Enabled { get; init; } = true;
    public ParticleSimulationMode SimulationMode { get; init; } =
        ParticleSimulationMode.Cpu;
    public bool Looping { get; init; } = true;
    public float Duration { get; init; } = 5.0f;
    public float EmissionRate { get; init; } = 12.0f;
    public uint BurstCount { get; init; }
    public uint MaxParticles { get; init; } = 256;
    public float LifetimeMin { get; init; } = 0.75f;
    public float LifetimeMax { get; init; } = 1.5f;
    public float SpeedMin { get; init; } = 0.5f;
    public float SpeedMax { get; init; } = 2.0f;
    public float StartSize { get; init; } = 0.25f;
    public float EndSize { get; init; }
    public UIColor StartColor { get; init; } = UIColor.White;
    public UIColor EndColor { get; init; } = new(255, 255, 255, 0);
    public Vector3 Direction { get; init; } = new(0.0f, 1.0f, 0.0f);
    public float SpreadAngleRadians { get; init; } = 0.35f;
    public Vector3 Acceleration { get; init; } = new(0.0f, -1.5f, 0.0f);
    public float Drag { get; init; }
    public float TurbulenceStrength { get; init; }
    public float TurbulenceFrequency { get; init; } = 1.0f;
    public float AngularVelocityMin { get; init; } = -1.0f;
    public float AngularVelocityMax { get; init; } = 1.0f;
    public string MeshAsset { get; init; } = "mesh-vfx-quad";
    public string MaterialAsset { get; init; } = "mat-vfx-default";
    public string RenderLayer { get; init; } = "Transparent";

    internal void Validate()
    {
        foreach (var (value, name) in new[]
        {
            (Duration, nameof(Duration)),
            (EmissionRate, nameof(EmissionRate)),
            (LifetimeMin, nameof(LifetimeMin)),
            (LifetimeMax, nameof(LifetimeMax)),
            (SpeedMin, nameof(SpeedMin)),
            (SpeedMax, nameof(SpeedMax)),
            (StartSize, nameof(StartSize)),
            (EndSize, nameof(EndSize)),
            (Drag, nameof(Drag)),
            (TurbulenceStrength, nameof(TurbulenceStrength)),
            (TurbulenceFrequency, nameof(TurbulenceFrequency)),
            (SpreadAngleRadians, nameof(SpreadAngleRadians)),
            (AngularVelocityMin, nameof(AngularVelocityMin)),
            (AngularVelocityMax, nameof(AngularVelocityMax))
        })
            RenderingScriptTools.Finite(value, name);
        RenderingScriptTools.Finite(Direction.X, nameof(Direction));
        RenderingScriptTools.Finite(Direction.Y, nameof(Direction));
        RenderingScriptTools.Finite(Direction.Z, nameof(Direction));
        RenderingScriptTools.Finite(Acceleration.X, nameof(Acceleration));
        RenderingScriptTools.Finite(Acceleration.Y, nameof(Acceleration));
        RenderingScriptTools.Finite(Acceleration.Z, nameof(Acceleration));
        if (Duration < 0.0f || EmissionRate < 0.0f || MaxParticles == 0 ||
            LifetimeMin <= 0.0f || LifetimeMax < LifetimeMin ||
            SpeedMax < SpeedMin || StartSize < 0.0f || EndSize < 0.0f ||
            Drag < 0.0f || TurbulenceStrength < 0.0f || TurbulenceFrequency <= 0.0f ||
            SpreadAngleRadians < 0.0f || SpreadAngleRadians > MathF.PI ||
            AngularVelocityMax < AngularVelocityMin)
            throw new ArgumentException("Particle emitter ranges are invalid.");
        RenderingScriptTools.AssetId(MeshAsset, nameof(MeshAsset));
        RenderingScriptTools.AssetId(MaterialAsset, nameof(MaterialAsset));
        RenderingScriptTools.AssetId(RenderLayer, nameof(RenderLayer));
    }
}

public static class RenderingScriptTools
{
    public const string LodGroupComponent = "engine.lod_group";
    public const string HlodClusterComponent = "engine.hlod_cluster";
    public const string ParticleEmitterComponent = "engine.vfx.particle_emitter";

    public static ComponentQuery QueryLodGroup(
        EngineBehaviour behaviour,
        string entityId) =>
        behaviour.Components.Query(entityId, LodGroupComponent);

    public static void ApplyLodGroup(
        EngineBehaviour behaviour,
        string entityId,
        LodGroupSettings settings)
    {
        ArgumentNullException.ThrowIfNull(behaviour);
        ArgumentNullException.ThrowIfNull(settings);
        settings.Validate();
        var levels = settings.Levels.Select(level =>
        {
            var fields = new Dictionary<string, ComponentValue>
            {
                ["distance"] = level.Distance,
                ["mesh"] = ComponentValue.FromAsset(level.MeshAsset)
            };
            if (level.MaterialAsset != null)
                fields["material"] = ComponentValue.FromAsset(level.MaterialAsset);
            return ComponentValue.FromMap(fields);
        }).ToArray();
        behaviour.Components.Set(
            entityId,
            LodGroupComponent,
            new Dictionary<string, ComponentValue>
            {
                ["minimum_distance"] = settings.MinimumDistance,
                ["cull_distance"] = settings.CullDistance,
                ["levels"] = ComponentValue.FromList(levels)
            });
    }

    public static ComponentQuery QueryHlodCluster(
        EngineBehaviour behaviour,
        string entityId) =>
        behaviour.Components.Query(entityId, HlodClusterComponent);

    public static void ApplyHlodCluster(
        EngineBehaviour behaviour,
        string entityId,
        HlodClusterSettings settings)
    {
        ArgumentNullException.ThrowIfNull(behaviour);
        ArgumentNullException.ThrowIfNull(settings);
        settings.Validate();
        behaviour.Components.Set(
            entityId,
            HlodClusterComponent,
            new Dictionary<string, ComponentValue>
            {
                ["cluster_id"] = settings.ClusterId,
                ["role"] = settings.Role == HlodRole.Proxy ? "proxy" : "source",
                ["activation_distance"] = settings.ActivationDistance,
                ["cull_distance"] = settings.CullDistance
            });
    }

    public static ComponentQuery QueryParticleEmitter(
        EngineBehaviour behaviour,
        string entityId) =>
        behaviour.Components.Query(entityId, ParticleEmitterComponent);

    /// Applying settings also restarts the emitter because component writes
    /// replace its non-serialized live-particle state at the frame boundary.
    public static void ApplyParticleEmitter(
        EngineBehaviour behaviour,
        string entityId,
        ParticleEmitterSettings settings)
    {
        ArgumentNullException.ThrowIfNull(behaviour);
        ArgumentNullException.ThrowIfNull(settings);
        settings.Validate();
        behaviour.Components.Set(
            entityId,
            ParticleEmitterComponent,
            new Dictionary<string, ComponentValue>
            {
                ["enabled"] = settings.Enabled,
                ["simulation_mode"] = ComponentValue.FromEnum(
                    settings.SimulationMode == ParticleSimulationMode.Gpu ? "gpu" : "cpu"),
                ["looping"] = settings.Looping,
                ["duration"] = settings.Duration,
                ["emission_rate"] = settings.EmissionRate,
                ["burst_count"] = settings.BurstCount,
                ["max_particles"] = settings.MaxParticles,
                ["lifetime_min"] = settings.LifetimeMin,
                ["lifetime_max"] = settings.LifetimeMax,
                ["speed_min"] = settings.SpeedMin,
                ["speed_max"] = settings.SpeedMax,
                ["start_size"] = settings.StartSize,
                ["end_size"] = settings.EndSize,
                ["start_color"] = ComponentValue.FromColor(
                    settings.StartColor.R / 255.0f,
                    settings.StartColor.G / 255.0f,
                    settings.StartColor.B / 255.0f,
                    settings.StartColor.A / 255.0f),
                ["end_color"] = ComponentValue.FromColor(
                    settings.EndColor.R / 255.0f,
                    settings.EndColor.G / 255.0f,
                    settings.EndColor.B / 255.0f,
                    settings.EndColor.A / 255.0f),
                ["direction"] = settings.Direction,
                ["spread_angle_radians"] = settings.SpreadAngleRadians,
                ["acceleration"] = settings.Acceleration,
                ["drag"] = settings.Drag,
                ["turbulence_strength"] = settings.TurbulenceStrength,
                ["turbulence_frequency"] = settings.TurbulenceFrequency,
                ["angular_velocity_min"] = settings.AngularVelocityMin,
                ["angular_velocity_max"] = settings.AngularVelocityMax,
                ["mesh_asset"] = ComponentValue.FromAsset(settings.MeshAsset),
                ["material_asset"] = ComponentValue.FromAsset(settings.MaterialAsset),
                ["render_layer"] = ComponentValue.FromEnum(settings.RenderLayer)
            });
    }

    internal static void Finite(float value, string parameterName)
    {
        if (!float.IsFinite(value))
            throw new ArgumentOutOfRangeException(parameterName, "Value must be finite.");
    }

    internal static void FiniteNonNegative(float value, string parameterName)
    {
        Finite(value, parameterName);
        if (value < 0.0f)
            throw new ArgumentOutOfRangeException(
                parameterName,
                "Value must be non-negative.");
    }

    internal static void AssetId(string? value, string parameterName)
    {
        if (string.IsNullOrWhiteSpace(value) || value.Length > 128 ||
            value.Any(char.IsControl))
            throw new ArgumentException(
                "Asset and layer ids must contain 1 to 128 visible characters.",
                parameterName);
    }
}
