// <auto-generated>
// Engine-owned runtime asset generation and volumetric terrain API.
// </auto-generated>
#nullable enable
using System.Text.Json.Serialization;
using System.Threading;

namespace Engine;

public readonly record struct RuntimeAssetRequest(uint RequestId);

public readonly record struct WorldPosition64(double X, double Y, double Z);

public readonly record struct RuntimeAssetResult(
    uint RequestId,
    string AssetId,
    bool Success,
    string? Error);

public sealed class RuntimeMeshData
{
    public required IReadOnlyList<Vector3> Positions { get; init; }
    public required IReadOnlyList<uint> Indices { get; init; }
    public IReadOnlyList<Vector3> Normals { get; init; } = Array.Empty<Vector3>();
    public IReadOnlyList<Vector2> UVs { get; init; } = Array.Empty<Vector2>();

    internal RuntimeMeshState ToState() => new()
    {
        Positions = Positions.Select(value => new[] { value.X, value.Y, value.Z }).ToArray(),
        Normals = Normals.Select(value => new[] { value.X, value.Y, value.Z }).ToArray(),
        UVs = UVs.Select(value => new[] { value.X, value.Y }).ToArray(),
        Indices = Indices.ToArray()
    };
}

public sealed class RuntimeMaterialData
{
    public float[] BaseColor { get; init; } = [1.0f, 1.0f, 1.0f, 1.0f];
    public float Metallic { get; init; }
    public float Roughness { get; init; } = 1.0f;
    public float AmbientOcclusion { get; init; } = 1.0f;
    public Vector3 Emissive { get; init; }
    public string? BaseColorTexture { get; init; }
    public string? NormalTexture { get; init; }
    public string? MetallicRoughnessTexture { get; init; }
    public string? OcclusionTexture { get; init; }
    public string? EmissiveTexture { get; init; }
    public bool DoubleSided { get; init; }
    public float? AlphaCutoff { get; init; }
    public bool Blend { get; init; }

    internal RuntimeMaterialState ToState()
    {
        if (BaseColor.Length != 4)
            throw new ArgumentException("BaseColor must contain exactly four channels.");
        return new RuntimeMaterialState
        {
            BaseColor = BaseColor.ToArray(),
            Metallic = Metallic,
            Roughness = Roughness,
            AmbientOcclusion = AmbientOcclusion,
            Emissive = [Emissive.X, Emissive.Y, Emissive.Z],
            BaseColorTexture = BaseColorTexture,
            NormalTexture = NormalTexture,
            MetallicRoughnessTexture = MetallicRoughnessTexture,
            OcclusionTexture = OcclusionTexture,
            EmissiveTexture = EmissiveTexture,
            DoubleSided = DoubleSided,
            AlphaCutoff = AlphaCutoff,
            Blend = Blend
        };
    }
}

public sealed class RuntimePrefabEntity
{
    public required string EntityId { get; init; }
    public string? Parent { get; init; }
    public string? Name { get; init; }
    public bool Enabled { get; init; } = true;
    public IReadOnlyDictionary<string, IReadOnlyDictionary<string, ComponentValue>> Components
        { get; init; } = new Dictionary<string, IReadOnlyDictionary<string, ComponentValue>>();

    internal RuntimePrefabEntityState ToState() => new()
    {
        EntityId = EntityId,
        Parent = Parent,
        Name = Name,
        Enabled = Enabled,
        Components = Components.ToDictionary(
            component => component.Key,
            component => component.Value.ToDictionary(
                field => field.Key,
                field => field.Value.ToState(),
                StringComparer.Ordinal),
            StringComparer.Ordinal)
    };
}

public sealed class ScriptRuntimeAssets
{
    private readonly List<GameplayCommandState> _pending = new();
    private Dictionary<uint, RuntimeAssetResult> _results = new();

    public RuntimeAssetRequest RegisterMesh(string assetId, RuntimeMeshData mesh)
    {
        ArgumentNullException.ThrowIfNull(mesh);
        var request = new RuntimeAssetRequest(RuntimeRequestIds.Next());
        _pending.Add(GameplayCommandState.RegisterRuntimeMesh(
            request.RequestId, assetId, mesh.ToState()));
        return request;
    }

    public RuntimeAssetRequest RegisterMaterial(string assetId, RuntimeMaterialData material)
    {
        ArgumentNullException.ThrowIfNull(material);
        var request = new RuntimeAssetRequest(RuntimeRequestIds.Next());
        _pending.Add(GameplayCommandState.RegisterRuntimeMaterial(
            request.RequestId, assetId, material.ToState()));
        return request;
    }

    public RuntimeAssetRequest RegisterPrefab(
        string assetId,
        IReadOnlyList<RuntimePrefabEntity> entities)
    {
        ArgumentNullException.ThrowIfNull(entities);
        var request = new RuntimeAssetRequest(RuntimeRequestIds.Next());
        _pending.Add(GameplayCommandState.RegisterRuntimePrefab(
            request.RequestId,
            assetId,
            new RuntimePrefabState { Entities = entities.Select(value => value.ToState()).ToArray() }));
        return request;
    }

    public bool TryGetResult(RuntimeAssetRequest request, out RuntimeAssetResult result) =>
        _results.TryGetValue(request.RequestId, out result);

    internal void Replace(IReadOnlyList<RuntimeAssetResultState> results) =>
        _results = results.ToDictionary(
            value => value.RequestId,
            value => new RuntimeAssetResult(
                value.RequestId, value.AssetId, value.Success, value.Error));

    internal void DrainTo(List<GameplayCommandState> commands)
    {
        commands.AddRange(_pending);
        _pending.Clear();
    }
}

public enum TerrainBrushMode
{
    Add,
    Subtract,
    Smooth,
    SetDensity
}

public sealed class ScriptTerrain
{
    private readonly List<GameplayCommandState> _pending = new();
    private Dictionary<uint, RuntimeAssetResult> _results = new();

    public RuntimeAssetRequest ApplyBrush(
        string terrainEntityId,
        WorldPosition64 center,
        double radius,
        float strength,
        TerrainBrushMode mode = TerrainBrushMode.Subtract,
        float targetDensity = 0.0f,
        ushort? material = null)
    {
        var request = new RuntimeAssetRequest(RuntimeRequestIds.Next());
        _pending.Add(GameplayCommandState.TerrainApplyBrush(
            request.RequestId,
            terrainEntityId,
            new TerrainBrushState
            {
                Center = [center.X, center.Y, center.Z],
                Radius = radius,
                Strength = strength,
                Mode = mode switch
                {
                    TerrainBrushMode.Add => "add",
                    TerrainBrushMode.Subtract => "subtract",
                    TerrainBrushMode.Smooth => "smooth",
                    TerrainBrushMode.SetDensity => "set_density",
                    _ => throw new ArgumentOutOfRangeException(nameof(mode))
                },
                TargetDensity = targetDensity,
                Material = material
            }));
        return request;
    }

    public bool TryGetResult(RuntimeAssetRequest request, out RuntimeAssetResult result) =>
        _results.TryGetValue(request.RequestId, out result);

    internal void Replace(IReadOnlyList<RuntimeAssetResultState> results) =>
        _results = results.ToDictionary(
            value => value.RequestId,
            value => new RuntimeAssetResult(
                value.RequestId, value.AssetId, value.Success, value.Error));

    internal void DrainTo(List<GameplayCommandState> commands)
    {
        commands.AddRange(_pending);
        _pending.Clear();
    }
}

internal static class RuntimeRequestIds
{
    private static int _next;
    internal static uint Next() => unchecked((uint)Interlocked.Increment(ref _next));
}

internal sealed class RuntimeAssetResultState
{
    [JsonPropertyName("request_id")]
    public uint RequestId { get; set; }
    [JsonPropertyName("asset_id")]
    public string AssetId { get; set; } = "";
    [JsonPropertyName("success")]
    public bool Success { get; set; }
    [JsonPropertyName("error")]
    public string? Error { get; set; }
}

internal sealed class RuntimeMeshState
{
    [JsonPropertyName("positions")]
    public required float[][] Positions { get; init; }
    [JsonPropertyName("normals")]
    public required float[][] Normals { get; init; }
    [JsonPropertyName("uvs")]
    public required float[][] UVs { get; init; }
    [JsonPropertyName("indices")]
    public required uint[] Indices { get; init; }
}

internal sealed class RuntimeMaterialState
{
    [JsonPropertyName("base_color")]
    public required float[] BaseColor { get; init; }
    [JsonPropertyName("metallic")]
    public float Metallic { get; init; }
    [JsonPropertyName("roughness")]
    public float Roughness { get; init; }
    [JsonPropertyName("ambient_occlusion")]
    public float AmbientOcclusion { get; init; }
    [JsonPropertyName("emissive")]
    public required float[] Emissive { get; init; }
    [JsonPropertyName("base_color_texture")]
    public string? BaseColorTexture { get; init; }
    [JsonPropertyName("normal_texture")]
    public string? NormalTexture { get; init; }
    [JsonPropertyName("metallic_roughness_texture")]
    public string? MetallicRoughnessTexture { get; init; }
    [JsonPropertyName("occlusion_texture")]
    public string? OcclusionTexture { get; init; }
    [JsonPropertyName("emissive_texture")]
    public string? EmissiveTexture { get; init; }
    [JsonPropertyName("double_sided")]
    public bool DoubleSided { get; init; }
    [JsonPropertyName("alpha_cutoff")]
    public float? AlphaCutoff { get; init; }
    [JsonPropertyName("blend")]
    public bool Blend { get; init; }
}

internal sealed class RuntimePrefabEntityState
{
    [JsonPropertyName("entity_id")]
    public required string EntityId { get; init; }
    [JsonPropertyName("parent")]
    public string? Parent { get; init; }
    [JsonPropertyName("name")]
    public string? Name { get; init; }
    [JsonPropertyName("enabled")]
    public bool Enabled { get; init; }
    [JsonPropertyName("components")]
    public required Dictionary<string, Dictionary<string, ComponentValueState>> Components
        { get; init; }
}

internal sealed class RuntimePrefabState
{
    [JsonPropertyName("entities")]
    public required RuntimePrefabEntityState[] Entities { get; init; }
}

internal sealed class TerrainBrushState
{
    [JsonPropertyName("center")]
    public required double[] Center { get; init; }
    [JsonPropertyName("radius")]
    public double Radius { get; init; }
    [JsonPropertyName("strength")]
    public float Strength { get; init; }
    [JsonPropertyName("mode")]
    public required string Mode { get; init; }
    [JsonPropertyName("target_density")]
    public float TargetDensity { get; init; }
    [JsonPropertyName("material")]
    public ushort? Material { get; init; }
}

public abstract partial class EngineBehaviour
{
    public ScriptRuntimeAssets RuntimeAssets { get; } = new();
    public ScriptTerrain Terrain { get; } = new();
}

internal sealed partial class GameplayContextState
{
    [JsonPropertyName("runtime_asset_results")]
    public List<RuntimeAssetResultState> RuntimeAssetResults { get; set; } = new();
}

internal sealed partial class GameplayCommandState
{
    [JsonPropertyName("request_id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public uint? RuntimeRequestId { get; init; }
    [JsonPropertyName("mesh")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public RuntimeMeshState? RuntimeMesh { get; init; }
    [JsonPropertyName("material")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public RuntimeMaterialState? RuntimeMaterial { get; init; }
    [JsonPropertyName("prefab")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public RuntimePrefabState? RuntimePrefab { get; init; }
    [JsonPropertyName("terrain_entity_id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? TerrainEntityId { get; init; }
    [JsonPropertyName("brush")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public TerrainBrushState? TerrainBrush { get; init; }

    public static GameplayCommandState RegisterRuntimeMesh(
        uint requestId, string assetId, RuntimeMeshState mesh) => new()
    {
        Type = "register_runtime_mesh",
        RuntimeRequestId = requestId,
        AssetId = assetId,
        RuntimeMesh = mesh
    };

    public static GameplayCommandState RegisterRuntimeMaterial(
        uint requestId, string assetId, RuntimeMaterialState material) => new()
    {
        Type = "register_runtime_material",
        RuntimeRequestId = requestId,
        AssetId = assetId,
        RuntimeMaterial = material
    };

    public static GameplayCommandState RegisterRuntimePrefab(
        uint requestId, string assetId, RuntimePrefabState prefab) => new()
    {
        Type = "register_runtime_prefab",
        RuntimeRequestId = requestId,
        AssetId = assetId,
        RuntimePrefab = prefab
    };

    public static GameplayCommandState TerrainApplyBrush(
        uint requestId, string terrainEntityId, TerrainBrushState brush) => new()
    {
        Type = "terrain_apply_brush",
        RuntimeRequestId = requestId,
        TerrainEntityId = terrainEntityId,
        TerrainBrush = brush
    };
}
