// <auto-generated>
// Shared deterministic primitives for engine-owned gameplay rule toolkits.
// </auto-generated>
#nullable enable
using System.Text.Json.Serialization;

namespace Engine.Gameplay;

/// Serializable deterministic random stream. Keep this algorithm in parity
/// with engine_gameplay::DeterministicRng.
public class DeterministicRandom
{
    [JsonInclude]
    public ulong State { get; private set; }

    public DeterministicRandom(ulong state) => State = state;

    public ulong NextUInt64()
    {
        unchecked
        {
            State += 0x9e3779b97f4a7c15UL;
            var value = State;
            value = (value ^ (value >> 30)) * 0xbf58476d1ce4e5b9UL;
            value = (value ^ (value >> 27)) * 0x94d049bb133111ebUL;
            return value ^ (value >> 31);
        }
    }

    public uint Range(uint upperExclusive) =>
        upperExclusive == 0 ? 0 : (uint)(NextUInt64() % upperExclusive);

    public int RollBasisPoints() => (int)Range(10_000);
}

public sealed record WeightedEntry<T>(T Value, uint Weight);

/// Stable weighted choice helper shared by encounter, loot, and AI tables.
public sealed class WeightedTable<T>
{
    private readonly List<WeightedEntry<T>> _entries = new();

    public IReadOnlyList<WeightedEntry<T>> Entries => _entries;

    public WeightedTable<T> Add(T value, uint weight)
    {
        if (weight == 0)
            throw new ArgumentOutOfRangeException(nameof(weight), "Weight must be positive.");
        _entries.Add(new WeightedEntry<T>(value, weight));
        return this;
    }

    public T Choose(DeterministicRandom random)
    {
        ArgumentNullException.ThrowIfNull(random);
        var total = _entries.Aggregate(
            0UL,
            (sum, entry) => checked(sum + entry.Weight));
        if (total == 0 || total > uint.MaxValue)
            throw new InvalidOperationException("Weighted table is empty or too large.");
        var roll = random.Range((uint)total);
        foreach (var entry in _entries)
        {
            if (roll < entry.Weight)
                return entry.Value;
            roll -= entry.Weight;
        }
        throw new InvalidOperationException("Weighted table selection failed.");
    }
}
