[package]
name = "engine-terrain"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = []

[dependencies]
crossbeam-channel.workspace = true
bincode.workspace = true
engine-procgen = { path = "../engine-procgen" }
engine-scene = { path = "../engine-scene" }
engine-serialize = { path = "../engine-serialize" }
glam.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
serde_json.workspace = true

[[bench]]
name = "planet_runtime"
harness = false
