// <auto-generated>
// Engine-owned ProcGen parity harness (ENG-10). Compiles the engine-owned
// gameplay SDK source (EngineGameplay.cs, produced by
// `sandbox project sync-script-api`) together with this file and checks the
// managed Engine.ProcGen port against the checked-in golden vectors shared
// with the Rust engine-procgen tests:
//
//   dotnet run --project ProcGenParity.csproj -- <path-to-golden_vectors.json>
//
// Exit code 0 means every derive_seed / noise / fBm / domain-warp vector
// matched bit-for-bit.
// </auto-generated>
using System.Text.Json;
using Engine;

if (args.Length != 1)
{
    Console.Error.WriteLine("usage: ProcGenParity <path-to-golden_vectors.json>");
    return 2;
}

int checks = 0;
int failures = 0;

void Check(bool condition, string label)
{
    checks++;
    if (!condition)
    {
        failures++;
        Console.Error.WriteLine($"MISMATCH: {label}");
    }
}

uint Bits(float value) => BitConverter.SingleToUInt32Bits(value);

ProcGenFbmParams ParseFbm(JsonElement element) => new(
    element.GetProperty("octaves").GetInt32(),
    element.GetProperty("frequency").GetSingle(),
    element.GetProperty("amplitude").GetSingle(),
    element.GetProperty("lacunarity").GetSingle(),
    element.GetProperty("gain").GetSingle(),
    element.GetProperty("offset")[0].GetSingle(),
    element.GetProperty("offset")[1].GetSingle(),
    element.GetProperty("offset")[2].GetSingle(),
    element.GetProperty("normalize").GetBoolean());

ProcGenWarpParams ParseWarp(JsonElement element) => new(
    element.GetProperty("amplitude").GetSingle(),
    element.GetProperty("frequency").GetSingle());

using var document = JsonDocument.Parse(await File.ReadAllTextAsync(args[0]));
var root = document.RootElement;

Check(root.GetProperty("schema").GetString() == "PROCGEN-GOLDEN-v1", "golden file schema tag");
Check(root.GetProperty("procgen_schema").GetString() == ProcGen.Schema, "procgen schema tag");

foreach (var vector in root.GetProperty("derive_seed").EnumerateArray())
{
    ulong parent = vector.GetProperty("parent").GetUInt64();
    string key = vector.GetProperty("key").GetString()!;
    ulong expected = vector.GetProperty("expected").GetUInt64();
    Check(ProcGen.DeriveSeed(parent, key) == expected, $"derive_seed({parent}, \"{key}\")");
}

foreach (var vector in root.GetProperty("noise2d").EnumerateArray())
{
    ulong seed = vector.GetProperty("seed").GetUInt64();
    var coords = vector.GetProperty("coords").EnumerateArray().ToArray();
    var expected = vector.GetProperty("expected_bits").EnumerateArray().ToArray();
    for (int i = 0; i < coords.Length; i++)
    {
        float x = coords[i][0].GetSingle();
        float y = coords[i][1].GetSingle();
        uint want = expected[i].GetUInt32();
        uint got = Bits(ProcGen.Noise2D(seed, x, y));
        Check(got == want, $"noise2d seed={seed} coord=({x}, {y}): got {got}, want {want}");
    }
}

foreach (var vector in root.GetProperty("noise3d").EnumerateArray())
{
    ulong seed = vector.GetProperty("seed").GetUInt64();
    var coords = vector.GetProperty("coords").EnumerateArray().ToArray();
    var expected = vector.GetProperty("expected_bits").EnumerateArray().ToArray();
    for (int i = 0; i < coords.Length; i++)
    {
        float x = coords[i][0].GetSingle();
        float y = coords[i][1].GetSingle();
        float z = coords[i][2].GetSingle();
        uint want = expected[i].GetUInt32();
        uint got = Bits(ProcGen.Noise3D(seed, x, y, z));
        Check(got == want, $"noise3d seed={seed} coord=({x}, {y}, {z}): got {got}, want {want}");
    }
}

foreach (var vector in root.GetProperty("fbm2d").EnumerateArray())
{
    ulong seed = vector.GetProperty("seed").GetUInt64();
    var parameters = ParseFbm(vector.GetProperty("params"));
    var coords = vector.GetProperty("coords").EnumerateArray().ToArray();
    var expected = vector.GetProperty("expected_bits").EnumerateArray().ToArray();
    for (int i = 0; i < coords.Length; i++)
    {
        float x = coords[i][0].GetSingle();
        float y = coords[i][1].GetSingle();
        uint want = expected[i].GetUInt32();
        uint got = Bits(ProcGen.Fbm2D(seed, x, y, parameters));
        Check(got == want, $"fbm2d seed={seed} coord=({x}, {y}): got {got}, want {want}");
    }
}

foreach (var vector in root.GetProperty("fbm3d").EnumerateArray())
{
    ulong seed = vector.GetProperty("seed").GetUInt64();
    var parameters = ParseFbm(vector.GetProperty("params"));
    var coords = vector.GetProperty("coords").EnumerateArray().ToArray();
    var expected = vector.GetProperty("expected_bits").EnumerateArray().ToArray();
    for (int i = 0; i < coords.Length; i++)
    {
        float x = coords[i][0].GetSingle();
        float y = coords[i][1].GetSingle();
        float z = coords[i][2].GetSingle();
        uint want = expected[i].GetUInt32();
        uint got = Bits(ProcGen.Fbm3D(seed, x, y, z, parameters));
        Check(got == want, $"fbm3d seed={seed} coord=({x}, {y}, {z}): got {got}, want {want}");
    }
}

foreach (var vector in root.GetProperty("warp2d").EnumerateArray())
{
    ulong seed = vector.GetProperty("seed").GetUInt64();
    var fbm = ParseFbm(vector.GetProperty("fbm"));
    var warp = ParseWarp(vector.GetProperty("warp"));
    var coords = vector.GetProperty("coords").EnumerateArray().ToArray();
    var expected = vector.GetProperty("expected_bits").EnumerateArray().ToArray();
    for (int i = 0; i < coords.Length; i++)
    {
        float x = coords[i][0].GetSingle();
        float y = coords[i][1].GetSingle();
        uint want = expected[i].GetUInt32();
        uint got = Bits(ProcGen.WarpedFbm2D(seed, x, y, fbm, warp));
        Check(got == want, $"warp2d seed={seed} coord=({x}, {y}): got {got}, want {want}");
    }
}

foreach (var vector in root.GetProperty("warp3d").EnumerateArray())
{
    ulong seed = vector.GetProperty("seed").GetUInt64();
    var fbm = ParseFbm(vector.GetProperty("fbm"));
    var warp = ParseWarp(vector.GetProperty("warp"));
    var coords = vector.GetProperty("coords").EnumerateArray().ToArray();
    var expected = vector.GetProperty("expected_bits").EnumerateArray().ToArray();
    for (int i = 0; i < coords.Length; i++)
    {
        float x = coords[i][0].GetSingle();
        float y = coords[i][1].GetSingle();
        float z = coords[i][2].GetSingle();
        uint want = expected[i].GetUInt32();
        uint got = Bits(ProcGen.WarpedFbm3D(seed, x, y, z, fbm, warp));
        Check(got == want, $"warp3d seed={seed} coord=({x}, {y}, {z}): got {got}, want {want}");
    }
}

Console.WriteLine($"procgen parity: {checks - failures}/{checks} checks passed");
return failures == 0 ? 0 : 1;
