//! Detects precompiled SPIR-V artifacts in `shaders/` and generates
//! a Rust source file exposing them as byte-slice constants.
//!
//! The shader toolchain stays external (per FD-004): the user runs `glslc`
//! against the GLSL files in `shaders/` to produce
//! matching `*.spv` files. When artifacts are missing the constants
//! resolve to empty slices so `cargo check` still passes; the renderer
//! surfaces a clear runtime error.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let shader_dir = manifest_dir.join("shaders");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let dest = out_dir.join("shaders_embedded.rs");

    println!("cargo:rerun-if-changed=shaders/forward.vert");
    println!("cargo:rerun-if-changed=shaders/forward.frag");
    println!("cargo:rerun-if-changed=shaders/skybox.vert");
    println!("cargo:rerun-if-changed=shaders/skybox.frag");
    println!("cargo:rerun-if-changed=shaders/shadow.vert");
    println!("cargo:rerun-if-changed=shaders/shadow.frag");
    println!("cargo:rerun-if-changed=shaders/skinned.vert");
    println!("cargo:rerun-if-changed=shaders/vfx_billboard.vert");
    println!("cargo:rerun-if-changed=shaders/gpu_vfx_billboard.vert");
    println!("cargo:rerun-if-changed=shaders/instanced.vert");
    println!("cargo:rerun-if-changed=shaders/tonemap.vert");
    println!("cargo:rerun-if-changed=shaders/tonemap.frag");
    println!("cargo:rerun-if-changed=shaders/ui_overlay.vert");
    println!("cargo:rerun-if-changed=shaders/ui_overlay.frag");
    println!("cargo:rerun-if-changed=shaders/skinned.vert.spv");
    println!("cargo:rerun-if-changed=shaders/vfx_billboard.vert.spv");
    println!("cargo:rerun-if-changed=shaders/gpu_vfx_billboard.vert.spv");
    println!("cargo:rerun-if-changed=shaders/vfx_billboard.frag.spv");
    println!("cargo:rerun-if-changed=shaders/instanced.vert.spv");
    println!("cargo:rerun-if-changed=shaders/forward.vert.spv");
    println!("cargo:rerun-if-changed=shaders/forward.frag.spv");
    println!("cargo:rerun-if-changed=shaders/skybox.vert.spv");
    println!("cargo:rerun-if-changed=shaders/skybox.frag.spv");
    println!("cargo:rerun-if-changed=shaders/shadow.vert.spv");
    println!("cargo:rerun-if-changed=shaders/shadow.frag.spv");
    println!("cargo:rerun-if-changed=shaders/tonemap.vert.spv");
    println!("cargo:rerun-if-changed=shaders/tonemap.frag.spv");
    println!("cargo:rerun-if-changed=shaders/ui_overlay.vert.spv");
    println!("cargo:rerun-if-changed=shaders/ui_overlay.frag.spv");

    let fwd_vert = entry("FORWARD_VERT_SPV", &shader_dir.join("forward.vert.spv"));
    let fwd_frag = entry("FORWARD_FRAG_SPV", &shader_dir.join("forward.frag.spv"));
    let skybox_vert = entry("SKYBOX_VERT_SPV", &shader_dir.join("skybox.vert.spv"));
    let skybox_frag = entry("SKYBOX_FRAG_SPV", &shader_dir.join("skybox.frag.spv"));
    let skin_vert = entry("SKINNED_VERT_SPV", &shader_dir.join("skinned.vert.spv"));
    let vfx_vert = entry(
        "VFX_BILLBOARD_VERT_SPV",
        &shader_dir.join("vfx_billboard.vert.spv"),
    );
    let gpu_vfx_vert = entry(
        "GPU_VFX_BILLBOARD_VERT_SPV",
        &shader_dir.join("gpu_vfx_billboard.vert.spv"),
    );
    let vfx_frag = entry(
        "VFX_BILLBOARD_FRAG_SPV",
        &shader_dir.join("vfx_billboard.frag.spv"),
    );
    let instanced_vert = entry("INSTANCED_VERT_SPV", &shader_dir.join("instanced.vert.spv"));
    let shad_vert = entry("SHADOW_VERT_SPV", &shader_dir.join("shadow.vert.spv"));
    let shad_frag = entry("SHADOW_FRAG_SPV", &shader_dir.join("shadow.frag.spv"));
    let tone_vert = entry("TONEMAP_VERT_SPV", &shader_dir.join("tonemap.vert.spv"));
    let tone_frag = entry("TONEMAP_FRAG_SPV", &shader_dir.join("tonemap.frag.spv"));
    let ui_vert = entry(
        "UI_OVERLAY_VERT_SPV",
        &shader_dir.join("ui_overlay.vert.spv"),
    );
    let ui_frag = entry(
        "UI_OVERLAY_FRAG_SPV",
        &shader_dir.join("ui_overlay.frag.spv"),
    );

    let contents = format!(
        "// Generated by build.rs. Do not edit.\n{fwd_vert}\n{fwd_frag}\n{skybox_vert}\n{skybox_frag}\n{skin_vert}\n{vfx_vert}\n{gpu_vfx_vert}\n{vfx_frag}\n{instanced_vert}\n{shad_vert}\n{shad_frag}\n{tone_vert}\n{tone_frag}\n{ui_vert}\n{ui_frag}\n",
        fwd_vert = fwd_vert, fwd_frag = fwd_frag,
        skybox_vert = skybox_vert, skybox_frag = skybox_frag,
        skin_vert = skin_vert,
        vfx_vert = vfx_vert,
        gpu_vfx_vert = gpu_vfx_vert,
        vfx_frag = vfx_frag,
        instanced_vert = instanced_vert,
        shad_vert = shad_vert, shad_frag = shad_frag,
        tone_vert = tone_vert, tone_frag = tone_frag,
        ui_vert = ui_vert, ui_frag = ui_frag,
    );
    fs::write(&dest, contents).expect("write shaders_embedded.rs");
}

fn entry(name: &str, path: &Path) -> String {
    if path.exists() {
        let display = path
            .canonicalize()
            .unwrap_or_else(|_| path.to_path_buf())
            .display()
            .to_string()
            .replace('\\', "\\\\");
        format!(
            "pub const {name}: &[u8] = include_bytes!(\"{display}\");",
            name = name,
            display = display
        )
    } else {
        println!(
            "cargo:warning=shader artifact {} is missing; runtime will refuse to start scenes that need it until it is compiled",
            path.display()
        );
        format!("pub const {name}: &[u8] = &[];", name = name)
    }
}
