//! Detects precompiled SPIR-V artifacts in `shaders/` and generates
//! a Rust source file exposing them as byte-slice constants.
//!
//! Gate 2 MVP keeps the shader toolchain external (per FD-004): the
//! user runs `glslc` against the GLSL files in `shaders/` to produce
//! matching `*.spv` files. When artifacts are missing the constants
//! resolve to empty slices so `cargo check` still passes; the renderer
//! surfaces a clear runtime error.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let shader_dir = manifest_dir.join("shaders");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let dest = out_dir.join("shaders_embedded.rs");

    println!("cargo:rerun-if-changed=shaders/triangle.vert");
    println!("cargo:rerun-if-changed=shaders/triangle.frag");
    println!("cargo:rerun-if-changed=shaders/textured.vert");
    println!("cargo:rerun-if-changed=shaders/textured.frag");
    println!("cargo:rerun-if-changed=shaders/forward.vert");
    println!("cargo:rerun-if-changed=shaders/forward.frag");
    println!("cargo:rerun-if-changed=shaders/shadow.vert");
    println!("cargo:rerun-if-changed=shaders/shadow.frag");
    println!("cargo:rerun-if-changed=shaders/skinned.vert");
    println!("cargo:rerun-if-changed=shaders/tonemap.vert");
    println!("cargo:rerun-if-changed=shaders/tonemap.frag");
    println!("cargo:rerun-if-changed=shaders/ui_overlay.vert");
    println!("cargo:rerun-if-changed=shaders/ui_overlay.frag");
    println!("cargo:rerun-if-changed=shaders/skinned.vert.spv");
    println!("cargo:rerun-if-changed=shaders/triangle.vert.spv");
    println!("cargo:rerun-if-changed=shaders/triangle.frag.spv");
    println!("cargo:rerun-if-changed=shaders/textured.vert.spv");
    println!("cargo:rerun-if-changed=shaders/textured.frag.spv");
    println!("cargo:rerun-if-changed=shaders/forward.vert.spv");
    println!("cargo:rerun-if-changed=shaders/forward.frag.spv");
    println!("cargo:rerun-if-changed=shaders/shadow.vert.spv");
    println!("cargo:rerun-if-changed=shaders/shadow.frag.spv");
    println!("cargo:rerun-if-changed=shaders/tonemap.vert.spv");
    println!("cargo:rerun-if-changed=shaders/tonemap.frag.spv");
    println!("cargo:rerun-if-changed=shaders/ui_overlay.vert.spv");
    println!("cargo:rerun-if-changed=shaders/ui_overlay.frag.spv");

    let vert = entry("TRIANGLE_VERT_SPV", &shader_dir.join("triangle.vert.spv"));
    let frag = entry("TRIANGLE_FRAG_SPV", &shader_dir.join("triangle.frag.spv"));
    let textured_vert = entry("TEXTURED_VERT_SPV", &shader_dir.join("textured.vert.spv"));
    let textured_frag = entry("TEXTURED_FRAG_SPV", &shader_dir.join("textured.frag.spv"));
    let fwd_vert = entry("FORWARD_VERT_SPV", &shader_dir.join("forward.vert.spv"));
    let fwd_frag = entry("FORWARD_FRAG_SPV", &shader_dir.join("forward.frag.spv"));
    let skin_vert = entry("SKINNED_VERT_SPV", &shader_dir.join("skinned.vert.spv"));
    let shad_vert = entry("SHADOW_VERT_SPV", &shader_dir.join("shadow.vert.spv"));
    let shad_frag = entry("SHADOW_FRAG_SPV", &shader_dir.join("shadow.frag.spv"));
    let tone_vert = entry("TONEMAP_VERT_SPV", &shader_dir.join("tonemap.vert.spv"));
    let tone_frag = entry("TONEMAP_FRAG_SPV", &shader_dir.join("tonemap.frag.spv"));
    let ui_vert = entry("UI_OVERLAY_VERT_SPV", &shader_dir.join("ui_overlay.vert.spv"));
    let ui_frag = entry("UI_OVERLAY_FRAG_SPV", &shader_dir.join("ui_overlay.frag.spv"));

    let contents = format!(
        "// Generated by build.rs. Do not edit.\n{vert}\n{frag}\n{textured_vert}\n{textured_frag}\n{fwd_vert}\n{fwd_frag}\n{skin_vert}\n{shad_vert}\n{shad_frag}\n{tone_vert}\n{tone_frag}\n{ui_vert}\n{ui_frag}\n",
        vert = vert, frag = frag,
        textured_vert = textured_vert, textured_frag = textured_frag,
        fwd_vert = fwd_vert, fwd_frag = fwd_frag,
        skin_vert = skin_vert,
        shad_vert = shad_vert, shad_frag = shad_frag,
        tone_vert = tone_vert, tone_frag = tone_frag,
        ui_vert = ui_vert, ui_frag = ui_frag,
    );
    fs::write(&dest, contents).expect("write shaders_embedded.rs");
}

fn entry(name: &str, path: &Path) -> String {
    if path.exists() {
        let display = path
            .canonicalize()
            .unwrap_or_else(|_| path.to_path_buf())
            .display()
            .to_string()
            .replace('\\', "\\\\");
        format!(
            "pub const {name}: &[u8] = include_bytes!(\"{display}\");",
            name = name,
            display = display
        )
    } else {
        println!(
            "cargo:warning=shader artifact {} is missing; runtime will refuse to start scenes that need it until it is compiled",
            path.display()
        );
        format!("pub const {name}: &[u8] = &[];", name = name)
    }
}
