//! Detects precompiled SPIR-V artifacts in `shaders/` and generates
//! a Rust source file exposing them as byte-slice constants.
//!
//! Gate 2 MVP keeps the shader toolchain external (per FD-004): the
//! user runs `glslc` against `shaders/triangle.vert` and
//! `shaders/triangle.frag` to produce `*.spv`. When the artifacts are
//! missing the constants resolve to empty slices so `cargo check`
//! still passes; the renderer surfaces a clear runtime error.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let shader_dir = manifest_dir.join("shaders");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let dest = out_dir.join("shaders_embedded.rs");

    println!("cargo:rerun-if-changed=shaders/triangle.vert");
    println!("cargo:rerun-if-changed=shaders/triangle.frag");
    println!("cargo:rerun-if-changed=shaders/triangle.vert.spv");
    println!("cargo:rerun-if-changed=shaders/triangle.frag.spv");

    let vert = entry("TRIANGLE_VERT_SPV", &shader_dir.join("triangle.vert.spv"));
    let frag = entry("TRIANGLE_FRAG_SPV", &shader_dir.join("triangle.frag.spv"));

    let contents = format!(
        "// Generated by build.rs. Do not edit.\n{vert}\n{frag}\n",
        vert = vert,
        frag = frag,
    );
    fs::write(&dest, contents).expect("write shaders_embedded.rs");
}

fn entry(name: &str, path: &Path) -> String {
    if path.exists() {
        let display = path
            .canonicalize()
            .unwrap_or_else(|_| path.to_path_buf())
            .display()
            .to_string()
            .replace('\\', "\\\\");
        format!(
            "pub const {name}: &[u8] = include_bytes!(\"{display}\");",
            name = name,
            display = display
        )
    } else {
        println!(
            "cargo:warning=shader artifact {} is missing; runtime will refuse to start the triangle scene until it is compiled",
            path.display()
        );
        format!("pub const {name}: &[u8] = &[];", name = name)
    }
}
