[package]
name = "engine-xr"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = []
openxr-runtime = ["dep:openxr"]

[dependencies]
glam.workspace = true
openxr = { workspace = true, optional = true }
serde.workspace = true
thiserror.workspace = true
