[package]
name = "sandbox"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = []
backend-vulkan = ["dep:render-vulkan", "engine-core/backend-vulkan"]
backend-opengl = ["dep:render-opengl"]
backend-dx12 = ["dep:render-dx12"]
runtime-subsystems = ["engine-core/runtime-subsystems", "dep:engine-ui"]
runtime-audio-output = ["engine-core/runtime-audio-output"]
tooling-editor = [
    "engine-editor/tooling-editor",
    "dep:engine-editor",
    "dep:engine-editor-host",
    "subsystem-scripting-csharp",
    "runtime-subsystems",
]
target-desktop = [
    "engine-core/gameplay",
    "runtime-subsystems",
    "runtime-audio-output",
]
target-mobile = []
subsystem-scripting-csharp = [
    "engine-core/subsystem-scripting-csharp",
    "engine-core/gameplay",
    "dep:engine-script",
    "runtime-subsystems",
]

[dependencies]
engine-animation = { path = "../engine-animation" }
engine-asset = { path = "../engine-asset" }
engine-character = { path = "../engine-character" }
engine-core = { path = "../engine-core" }
engine-ui = { path = "../engine-ui", optional = true }
engine-gameplay = { path = "../engine-gameplay" }
engine-physics = { path = "../engine-physics" }
engine-editor = { path = "../engine-editor", optional = true }
engine-editor-host = { path = "../engine-editor-host", optional = true }
engine-renderer = { path = "../engine-renderer" }
engine-scene = { path = "../engine-scene" }
engine-script = { path = "../engine-script", optional = true }
engine-script-api = { path = "../engine-script-api" }
engine-serialize = { path = "../engine-serialize" }
glam.workspace = true
gltf.workspace = true
render-core = { path = "../render-core" }
platform = { path = "../platform" }
raw-window-handle.workspace = true
ron.workspace = true
render-vulkan = { path = "../render-vulkan", optional = true }
render-opengl = { path = "../render-opengl", optional = true }
render-dx12 = { path = "../render-dx12", optional = true }
tracing.workspace = true
tracing-subscriber.workspace = true
serde_json.workspace = true
serde.workspace = true
sha2.workspace = true
tempfile = "3"

[dev-dependencies]
bincode.workspace = true
engine-audio = { path = "../engine-audio" }
engine-nav = { path = "../engine-nav" }

[build-dependencies]
serde_json.workspace = true
sha2.workspace = true
