use std::cmp::Ordering;
use std::collections::{BTreeMap, BTreeSet, BinaryHeap, VecDeque};
use std::sync::Arc;
use std::thread::{self, JoinHandle};
use std::time::{Duration, Instant};

use crossbeam_channel::{Receiver, Sender};

use crate::{TerrainChunkData, TerrainChunkId, TerrainChunkRequest, TerrainChunkState};

pub trait TerrainChunkGenerator: Send + Sync + 'static {
    fn generate(&self, request: &TerrainChunkRequest) -> Result<TerrainChunkData, String>;
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct TerrainRuntimeConfig {
    pub worker_count: usize,
    pub max_in_flight: usize,
    /// Maximum generated bytes made visible to the host per tick. One
    /// oversized chunk is still committed to prevent starvation.
    pub commit_budget_bytes: usize,
    /// Maximum generated CPU payload retained as resident cache.
    pub cache_budget_bytes: usize,
}

impl Default for TerrainRuntimeConfig {
    fn default() -> Self {
        Self {
            worker_count: 2,
            max_in_flight: 4,
            commit_budget_bytes: 8 * 1024 * 1024,
            cache_budget_bytes: 256 * 1024 * 1024,
        }
    }
}

impl TerrainRuntimeConfig {
    fn normalized(mut self) -> Self {
        self.worker_count = self.worker_count.clamp(1, 64);
        self.max_in_flight = self.max_in_flight.max(1);
        self.commit_budget_bytes = self.commit_budget_bytes.max(1);
        self.cache_budget_bytes = self.cache_budget_bytes.max(1);
        self
    }
}

#[derive(Clone, Debug)]
pub enum TerrainRuntimeEvent {
    Ready(Arc<TerrainChunkData>),
    Unload(TerrainChunkId),
    Failed {
        id: TerrainChunkId,
        revision: u64,
        message: String,
    },
}

#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct TerrainRuntimeStats {
    pub queued: usize,
    pub generating: usize,
    pub ready_to_commit: usize,
    pub resident: usize,
    pub failed: usize,
    pub resident_bytes: usize,
    pub stale_results_discarded: u64,
    pub cancelled: u64,
    pub generated: u64,
    pub committed: u64,
    pub evicted: u64,
    pub last_tick_committed_bytes: usize,
    pub last_generation_micros: u64,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct TerrainChunkDebugInfo {
    pub id: TerrainChunkId,
    pub revision: u64,
    pub priority: u32,
    pub state: TerrainChunkState,
    pub resident_bytes: usize,
    pub error: Option<String>,
}

#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct TerrainDebugSnapshot {
    pub stats: TerrainRuntimeStats,
    pub chunks: Vec<TerrainChunkDebugInfo>,
}

struct Entry {
    request: TerrainChunkRequest,
    state: TerrainChunkState,
    resident: Option<Arc<TerrainChunkData>>,
    error: Option<String>,
    sequence: u64,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
struct QueueKey {
    priority: u32,
    sequence: u64,
    id: TerrainChunkId,
    revision: u64,
}

impl Ord for QueueKey {
    fn cmp(&self, other: &Self) -> Ordering {
        // BinaryHeap pops greatest; reverse priority/sequence for FIFO at the
        // lowest numeric priority.
        other
            .priority
            .cmp(&self.priority)
            .then_with(|| other.sequence.cmp(&self.sequence))
            .then_with(|| self.id.cmp(&other.id))
    }
}

impl PartialOrd for QueueKey {
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}

struct WorkResult {
    id: TerrainChunkId,
    revision: u64,
    elapsed: Duration,
    result: Result<TerrainChunkData, String>,
}

pub struct TerrainRuntime<G: TerrainChunkGenerator> {
    config: TerrainRuntimeConfig,
    entries: BTreeMap<TerrainChunkId, Entry>,
    pending: BinaryHeap<QueueKey>,
    completed: VecDeque<WorkResult>,
    request_tx: Option<Sender<TerrainChunkRequest>>,
    result_rx: Receiver<WorkResult>,
    workers: Vec<JoinHandle<()>>,
    in_flight: usize,
    next_sequence: u64,
    counters: TerrainRuntimeStats,
    _generator: std::marker::PhantomData<G>,
}

impl<G: TerrainChunkGenerator> TerrainRuntime<G> {
    pub fn new(generator: G, config: TerrainRuntimeConfig) -> Self {
        let config = config.normalized();
        let (request_tx, request_rx) = crossbeam_channel::unbounded::<TerrainChunkRequest>();
        let (result_tx, result_rx) = crossbeam_channel::unbounded::<WorkResult>();
        let generator = Arc::new(generator);
        let mut workers = Vec::with_capacity(config.worker_count);
        for index in 0..config.worker_count {
            let requests = request_rx.clone();
            let results = result_tx.clone();
            let generator = Arc::clone(&generator);
            workers.push(
                thread::Builder::new()
                    .name(format!("terrain-worker-{index}"))
                    .spawn(move || worker_loop(generator, requests, results))
                    .expect("terrain worker thread must spawn"),
            );
        }
        drop(result_tx);
        Self {
            config,
            entries: BTreeMap::new(),
            pending: BinaryHeap::new(),
            completed: VecDeque::new(),
            request_tx: Some(request_tx),
            result_rx,
            workers,
            in_flight: 0,
            next_sequence: 0,
            counters: TerrainRuntimeStats::default(),
            _generator: std::marker::PhantomData,
        }
    }

    pub fn config(&self) -> &TerrainRuntimeConfig {
        &self.config
    }

    /// Reconcile the complete desired set. Missing chunks are cancelled or
    /// unloaded; same-id/same-revision requests retain their current work.
    pub fn set_desired<I>(&mut self, requests: I) -> Vec<TerrainRuntimeEvent>
    where
        I: IntoIterator<Item = TerrainChunkRequest>,
    {
        let requests = requests.into_iter().collect::<Vec<_>>();
        let desired = requests
            .iter()
            .map(|request| request.id)
            .collect::<BTreeSet<_>>();
        let mut events = Vec::new();
        let removed = self
            .entries
            .keys()
            .copied()
            .filter(|id| !desired.contains(id))
            .collect::<Vec<_>>();
        for id in removed {
            if let Some(entry) = self.entries.remove(&id) {
                if matches!(
                    entry.state,
                    TerrainChunkState::Generating | TerrainChunkState::Queued
                ) {
                    self.counters.cancelled += 1;
                }
                if entry.state == TerrainChunkState::Resident {
                    events.push(TerrainRuntimeEvent::Unload(id));
                }
            }
        }

        for request in requests {
            let unchanged = self
                .entries
                .get(&request.id)
                .is_some_and(|entry| entry.request.revision == request.revision);
            if unchanged {
                if let Some(entry) = self.entries.get_mut(&request.id) {
                    if entry.state == TerrainChunkState::Queued
                        && entry.request.priority != request.priority
                    {
                        let sequence = self.next_sequence;
                        self.next_sequence = self.next_sequence.wrapping_add(1);
                        entry.sequence = sequence;
                        self.pending.push(QueueKey {
                            priority: request.priority,
                            sequence,
                            id: request.id,
                            revision: request.revision,
                        });
                    }
                    entry.request.priority = request.priority;
                    entry.request.volume = request.volume;
                }
                continue;
            }
            if self
                .entries
                .get(&request.id)
                .is_some_and(|entry| entry.state == TerrainChunkState::Resident)
            {
                events.push(TerrainRuntimeEvent::Unload(request.id));
            }
            let sequence = self.next_sequence;
            self.next_sequence = self.next_sequence.wrapping_add(1);
            self.pending.push(QueueKey {
                priority: request.priority,
                sequence,
                id: request.id,
                revision: request.revision,
            });
            self.entries.insert(
                request.id,
                Entry {
                    request,
                    state: TerrainChunkState::Queued,
                    resident: None,
                    error: None,
                    sequence,
                },
            );
        }
        events
    }

    /// Poll workers, dispatch priority work, and commit within the byte
    /// budget. Call once at a main-thread frame boundary.
    pub fn tick(&mut self) -> Vec<TerrainRuntimeEvent> {
        self.collect_worker_results();
        self.dispatch_work();
        self.collect_worker_results();
        let mut events = self.commit_completed();
        events.extend(self.enforce_cache_budget());
        self.refresh_counts();
        events
    }

    pub fn snapshot(&self) -> TerrainDebugSnapshot {
        let mut stats = self.counters.clone();
        populate_counts(&self.entries, &mut stats);
        TerrainDebugSnapshot {
            stats,
            chunks: self
                .entries
                .values()
                .map(|entry| TerrainChunkDebugInfo {
                    id: entry.request.id,
                    revision: entry.request.revision,
                    priority: entry.request.priority,
                    state: entry.state,
                    resident_bytes: entry
                        .resident
                        .as_ref()
                        .map_or(0, |data| data.estimated_bytes()),
                    error: entry.error.clone(),
                })
                .collect(),
        }
    }

    /// Retry failed chunks without changing their recipe revision.
    pub fn retry_failed(&mut self) {
        let failed = self
            .entries
            .iter()
            .filter_map(|(id, entry)| (entry.state == TerrainChunkState::Failed).then_some(*id))
            .collect::<Vec<_>>();
        for id in failed {
            let sequence = self.next_sequence;
            self.next_sequence = self.next_sequence.wrapping_add(1);
            if let Some(entry) = self.entries.get_mut(&id) {
                entry.state = TerrainChunkState::Queued;
                entry.error = None;
                entry.sequence = sequence;
                self.pending.push(QueueKey {
                    priority: entry.request.priority,
                    sequence,
                    id,
                    revision: entry.request.revision,
                });
            }
        }
    }

    /// Acknowledge that the host successfully created the render/physics
    /// resources for a delivered [`TerrainRuntimeEvent::Ready`] payload.
    ///
    /// Until this call, the entry remains `ReadyToCommit`, so a host-side
    /// failure cannot be mistaken for a resident chunk.
    pub fn commit_succeeded(&mut self, id: TerrainChunkId, revision: u64) -> bool {
        let Some(entry) = self.entries.get_mut(&id) else {
            return false;
        };
        if entry.request.revision != revision || entry.state != TerrainChunkState::ReadyToCommit {
            return false;
        }
        entry.state = TerrainChunkState::Resident;
        entry.error = None;
        self.counters.committed += 1;
        true
    }

    /// Reject a delivered payload after the host failed to create its
    /// render/physics resources. The chunk remains failed until an explicit
    /// [`retry_failed`](Self::retry_failed) call or a recipe revision change.
    pub fn commit_failed(
        &mut self,
        id: TerrainChunkId,
        revision: u64,
        message: impl Into<String>,
    ) -> bool {
        let Some(entry) = self.entries.get_mut(&id) else {
            return false;
        };
        if entry.request.revision != revision || entry.state != TerrainChunkState::ReadyToCommit {
            return false;
        }
        entry.state = TerrainChunkState::Failed;
        entry.resident = None;
        entry.error = Some(message.into());
        true
    }

    fn dispatch_work(&mut self) {
        while self.in_flight < self.config.max_in_flight {
            let Some(key) = self.pending.pop() else {
                break;
            };
            let Some(entry) = self.entries.get_mut(&key.id) else {
                continue;
            };
            if entry.state != TerrainChunkState::Queued
                || entry.request.revision != key.revision
                || entry.sequence != key.sequence
            {
                continue;
            }
            let request = entry.request.clone();
            let sent = self
                .request_tx
                .as_ref()
                .is_some_and(|sender| sender.send(request).is_ok());
            if sent {
                entry.state = TerrainChunkState::Generating;
                self.in_flight += 1;
            } else {
                entry.state = TerrainChunkState::Failed;
                entry.error = Some("terrain worker queue disconnected".into());
            }
        }
    }

    fn collect_worker_results(&mut self) {
        while let Ok(result) = self.result_rx.try_recv() {
            self.in_flight = self.in_flight.saturating_sub(1);
            self.counters.generated += 1;
            self.counters.last_generation_micros =
                result.elapsed.as_micros().min(u128::from(u64::MAX)) as u64;
            let current = self.entries.get(&result.id).is_some_and(|entry| {
                entry.request.revision == result.revision
                    && entry.state == TerrainChunkState::Generating
            });
            if current {
                if let Some(entry) = self.entries.get_mut(&result.id) {
                    entry.state = match &result.result {
                        Ok(_) => TerrainChunkState::ReadyToCommit,
                        Err(message) => {
                            entry.error = Some(message.clone());
                            TerrainChunkState::Failed
                        }
                    };
                }
                self.completed.push_back(result);
            } else {
                self.counters.stale_results_discarded += 1;
            }
        }
    }

    fn commit_completed(&mut self) -> Vec<TerrainRuntimeEvent> {
        let mut events = Vec::new();
        let mut committed_bytes = 0usize;
        while let Some(result) = self.completed.front() {
            let bytes = result
                .result
                .as_ref()
                .map_or(0, TerrainChunkData::estimated_bytes);
            if committed_bytes > 0
                && committed_bytes.saturating_add(bytes) > self.config.commit_budget_bytes
            {
                break;
            }
            let result = self.completed.pop_front().expect("front existed");
            let Some(entry) = self.entries.get_mut(&result.id) else {
                self.counters.stale_results_discarded += 1;
                continue;
            };
            if entry.request.revision != result.revision {
                self.counters.stale_results_discarded += 1;
                continue;
            }
            match result.result {
                Ok(data) => {
                    let data = Arc::new(data);
                    committed_bytes = committed_bytes.saturating_add(data.estimated_bytes());
                    entry.resident = Some(Arc::clone(&data));
                    // The host must acknowledge resource creation before this
                    // becomes Resident. This makes mesh/collider commit a
                    // proper two-phase operation.
                    entry.state = TerrainChunkState::ReadyToCommit;
                    entry.error = None;
                    events.push(TerrainRuntimeEvent::Ready(data));
                }
                Err(message) => {
                    entry.state = TerrainChunkState::Failed;
                    entry.error = Some(message.clone());
                    events.push(TerrainRuntimeEvent::Failed {
                        id: result.id,
                        revision: result.revision,
                        message,
                    });
                }
            }
        }
        self.counters.last_tick_committed_bytes = committed_bytes;
        events
    }

    fn enforce_cache_budget(&mut self) -> Vec<TerrainRuntimeEvent> {
        let mut bytes = self
            .entries
            .values()
            .filter_map(|entry| entry.resident.as_ref())
            .map(|data| data.estimated_bytes())
            .sum::<usize>();
        while bytes > self.config.cache_budget_bytes {
            let victim = self
                .entries
                .iter()
                .filter(|(_, entry)| {
                    entry.state == TerrainChunkState::Resident && entry.resident.is_some()
                })
                .max_by_key(|(_, entry)| (entry.request.priority, entry.sequence))
                .map(|(id, _)| *id);
            let Some(id) = victim else {
                break;
            };
            let entry = self.entries.get_mut(&id).expect("victim existed");
            bytes = bytes.saturating_sub(
                entry
                    .resident
                    .take()
                    .as_ref()
                    .map_or(0, |data| data.estimated_bytes()),
            );
            self.counters.evicted += 1;
        }
        Vec::new()
    }

    fn refresh_counts(&mut self) {
        populate_counts(&self.entries, &mut self.counters);
    }
}

impl<G: TerrainChunkGenerator> Drop for TerrainRuntime<G> {
    fn drop(&mut self) {
        self.request_tx.take();
        for worker in self.workers.drain(..) {
            let _ = worker.join();
        }
    }
}

fn worker_loop<G: TerrainChunkGenerator>(
    generator: Arc<G>,
    requests: Receiver<TerrainChunkRequest>,
    results: Sender<WorkResult>,
) {
    while let Ok(request) = requests.recv() {
        let id = request.id;
        let revision = request.revision;
        let started = Instant::now();
        let result = generator.generate(&request);
        if results
            .send(WorkResult {
                id,
                revision,
                elapsed: started.elapsed(),
                result,
            })
            .is_err()
        {
            break;
        }
    }
}

fn populate_counts(entries: &BTreeMap<TerrainChunkId, Entry>, stats: &mut TerrainRuntimeStats) {
    stats.queued = 0;
    stats.generating = 0;
    stats.ready_to_commit = 0;
    stats.resident = 0;
    stats.failed = 0;
    stats.resident_bytes = 0;
    for entry in entries.values() {
        match entry.state {
            TerrainChunkState::Queued => stats.queued += 1,
            TerrainChunkState::Generating => stats.generating += 1,
            TerrainChunkState::ReadyToCommit => stats.ready_to_commit += 1,
            TerrainChunkState::Resident => stats.resident += 1,
            TerrainChunkState::Failed => stats.failed += 1,
        }
        stats.resident_bytes += entry
            .resident
            .as_ref()
            .map_or(0, |data| data.estimated_bytes());
    }
}

#[cfg(test)]
mod tests {
    use std::sync::atomic::{AtomicUsize, Ordering};
    use std::sync::Mutex;

    use super::*;
    use crate::{TerrainCollisionData, TerrainMeshData, TerrainVolume, TerrainVolumeId};

    #[derive(Clone)]
    struct StubGenerator;

    impl TerrainChunkGenerator for StubGenerator {
        fn generate(&self, request: &TerrainChunkRequest) -> Result<TerrainChunkData, String> {
            Ok(TerrainChunkData {
                id: request.id,
                revision: request.revision,
                origin: [0.0; 3],
                local_center: [0.0; 3],
                mesh: TerrainMeshData {
                    positions: vec![[0.0; 3]; 4],
                    normals: vec![[0.0, 1.0, 0.0]; 4],
                    uvs: vec![[0.0; 2]; 4],
                    indices: vec![0, 1, 2],
                    bounds_min: [0.0; 3],
                    bounds_max: [1.0; 3],
                },
                geomorph: None,
                collision: Some(TerrainCollisionData {
                    rows: 2,
                    columns: 2,
                    heights: vec![0.0; 4],
                    sample_spacing: 1.0,
                }),
                triangle_collision: None,
            })
        }
    }

    fn request(x: i64, revision: u64, priority: u32) -> TerrainChunkRequest {
        TerrainChunkRequest {
            id: TerrainChunkId::new(x, 0, 0),
            revision,
            priority,
            volume: TerrainVolume::default(),
        }
    }

    fn request_for_volume(
        volume_id: TerrainVolumeId,
        revision: u64,
        priority: u32,
    ) -> TerrainChunkRequest {
        TerrainChunkRequest {
            id: TerrainChunkId::for_volume(volume_id, 0, 0, 0),
            revision,
            priority,
            volume: TerrainVolume::default(),
        }
    }

    fn tick_until<G: TerrainChunkGenerator>(
        runtime: &mut TerrainRuntime<G>,
        expected: usize,
    ) -> Vec<TerrainRuntimeEvent> {
        let deadline = Instant::now() + Duration::from_secs(2);
        let mut events = Vec::new();
        while events
            .iter()
            .filter(|event| matches!(event, TerrainRuntimeEvent::Ready(_)))
            .count()
            < expected
        {
            events.extend(runtime.tick());
            assert!(Instant::now() < deadline, "terrain worker timed out");
            thread::yield_now();
        }
        events
    }

    fn acknowledge_ready<G: TerrainChunkGenerator>(
        runtime: &mut TerrainRuntime<G>,
        events: &[TerrainRuntimeEvent],
    ) {
        for event in events {
            if let TerrainRuntimeEvent::Ready(data) = event {
                assert!(runtime.commit_succeeded(data.id, data.revision));
            }
        }
    }

    #[test]
    fn runtime_commits_generated_chunks() {
        let mut runtime = TerrainRuntime::new(StubGenerator, TerrainRuntimeConfig::default());
        runtime.set_desired([request(0, 1, 0)]);
        let events = tick_until(&mut runtime, 1);
        assert!(matches!(events.last(), Some(TerrainRuntimeEvent::Ready(_))));
        assert_eq!(runtime.snapshot().stats.ready_to_commit, 1);
        acknowledge_ready(&mut runtime, &events);
        assert_eq!(runtime.snapshot().stats.resident, 1);
        assert_eq!(runtime.snapshot().stats.committed, 1);
    }

    #[test]
    fn identical_coordinates_from_two_volumes_stream_and_unload_independently() {
        let first_id = TerrainVolumeId::from_persistent_id("planet:first");
        let second_id = TerrainVolumeId::from_persistent_id("planet:second");
        let first = request_for_volume(first_id, 1, 0);
        let second = request_for_volume(second_id, 1, 1);
        let mut runtime = TerrainRuntime::new(
            StubGenerator,
            TerrainRuntimeConfig {
                worker_count: 1,
                max_in_flight: 2,
                cache_budget_bytes: 1,
                ..TerrainRuntimeConfig::default()
            },
        );

        runtime.set_desired([first.clone(), second.clone()]);
        let ready = tick_until(&mut runtime, 2);
        assert_eq!(
            ready
                .iter()
                .filter_map(|event| match event {
                    TerrainRuntimeEvent::Ready(data) => Some(data.id.volume_id),
                    _ => None,
                })
                .collect::<BTreeSet<_>>(),
            BTreeSet::from([first_id, second_id])
        );
        acknowledge_ready(&mut runtime, &ready);
        runtime.tick();
        let resident = runtime.snapshot();
        assert_eq!(resident.stats.resident, 2);
        assert_eq!(resident.stats.resident_bytes, 0);

        let events = runtime.set_desired([second]);
        assert_eq!(
            events
                .iter()
                .filter_map(|event| match event {
                    TerrainRuntimeEvent::Unload(id) => Some(id.volume_id),
                    _ => None,
                })
                .collect::<Vec<_>>(),
            [first_id]
        );
        let snapshot = runtime.snapshot();
        assert_eq!(snapshot.stats.resident, 1);
        assert_eq!(snapshot.chunks[0].id.volume_id, second_id);
    }

    #[test]
    fn host_commit_failure_never_becomes_resident() {
        let mut runtime = TerrainRuntime::new(StubGenerator, TerrainRuntimeConfig::default());
        runtime.set_desired([request(0, 1, 0)]);
        let events = tick_until(&mut runtime, 1);
        let data = events
            .iter()
            .find_map(|event| match event {
                TerrainRuntimeEvent::Ready(data) => Some(data),
                _ => None,
            })
            .expect("ready payload");
        assert!(runtime.commit_failed(data.id, data.revision, "mesh upload failed"));
        let snapshot = runtime.snapshot();
        assert_eq!(snapshot.stats.resident, 0);
        assert_eq!(snapshot.stats.failed, 1);
        assert_eq!(snapshot.stats.committed, 0);
        assert_eq!(
            snapshot.chunks[0].error.as_deref(),
            Some("mesh upload failed")
        );
    }

    #[test]
    fn cancellation_unloads_resident_and_stale_work_is_ignored() {
        let mut runtime = TerrainRuntime::new(StubGenerator, TerrainRuntimeConfig::default());
        runtime.set_desired([request(0, 1, 0)]);
        let ready = tick_until(&mut runtime, 1);
        acknowledge_ready(&mut runtime, &ready);
        let events = runtime.set_desired(std::iter::empty());
        assert_eq!(events.len(), 1);
        assert!(matches!(events[0], TerrainRuntimeEvent::Unload(_)));
        assert_eq!(runtime.snapshot().stats.resident, 0);
    }

    #[test]
    fn revision_replaces_old_resident() {
        let mut runtime = TerrainRuntime::new(StubGenerator, TerrainRuntimeConfig::default());
        runtime.set_desired([request(0, 1, 0)]);
        let ready = tick_until(&mut runtime, 1);
        acknowledge_ready(&mut runtime, &ready);
        let events = runtime.set_desired([request(0, 2, 0)]);
        assert!(events
            .iter()
            .any(|event| matches!(event, TerrainRuntimeEvent::Unload(_))));
        let events = tick_until(&mut runtime, 1);
        assert!(events
            .iter()
            .any(|event| matches!(event, TerrainRuntimeEvent::Ready(data) if data.revision == 2)));
    }

    #[test]
    fn cache_eviction_drops_cpu_payload_without_unloading_or_regenerating() {
        let mut runtime = TerrainRuntime::new(
            StubGenerator,
            TerrainRuntimeConfig {
                cache_budget_bytes: 1,
                ..TerrainRuntimeConfig::default()
            },
        );
        let desired = request(0, 1, 0);
        runtime.set_desired([desired.clone()]);
        let ready = tick_until(&mut runtime, 1);
        acknowledge_ready(&mut runtime, &ready);

        assert!(runtime.tick().is_empty());
        let after_eviction = runtime.snapshot();
        assert_eq!(after_eviction.stats.resident, 1);
        assert_eq!(after_eviction.stats.resident_bytes, 0);
        assert_eq!(after_eviction.stats.evicted, 1);
        let generated = after_eviction.stats.generated;

        for _ in 0..4 {
            assert!(runtime.set_desired([desired.clone()]).is_empty());
            assert!(runtime.tick().is_empty());
        }
        assert_eq!(runtime.snapshot().stats.generated, generated);
    }

    #[derive(Clone)]
    struct FailingGenerator {
        calls: Arc<AtomicUsize>,
    }

    impl TerrainChunkGenerator for FailingGenerator {
        fn generate(&self, _: &TerrainChunkRequest) -> Result<TerrainChunkData, String> {
            self.calls.fetch_add(1, Ordering::SeqCst);
            Err("permanent failure".to_string())
        }
    }

    #[test]
    fn failed_work_waits_for_explicit_retry() {
        let calls = Arc::new(AtomicUsize::new(0));
        let mut runtime = TerrainRuntime::new(
            FailingGenerator {
                calls: Arc::clone(&calls),
            },
            TerrainRuntimeConfig {
                worker_count: 1,
                max_in_flight: 1,
                ..TerrainRuntimeConfig::default()
            },
        );
        let desired = request(0, 1, 0);
        runtime.set_desired([desired.clone()]);
        let deadline = Instant::now() + Duration::from_secs(2);
        while runtime.snapshot().stats.failed == 0 {
            runtime.tick();
            assert!(Instant::now() < deadline, "failure result timed out");
            thread::yield_now();
        }
        assert_eq!(calls.load(Ordering::SeqCst), 1);

        for _ in 0..4 {
            runtime.set_desired([desired.clone()]);
            runtime.tick();
        }
        assert_eq!(calls.load(Ordering::SeqCst), 1);

        runtime.retry_failed();
        let deadline = Instant::now() + Duration::from_secs(2);
        while calls.load(Ordering::SeqCst) < 2 {
            runtime.tick();
            assert!(Instant::now() < deadline, "retry result timed out");
            thread::yield_now();
        }
    }

    #[derive(Clone)]
    struct RecordingGenerator {
        order: Arc<Mutex<Vec<i64>>>,
    }

    impl TerrainChunkGenerator for RecordingGenerator {
        fn generate(&self, request: &TerrainChunkRequest) -> Result<TerrainChunkData, String> {
            self.order.lock().unwrap().push(request.id.x);
            StubGenerator.generate(request)
        }
    }

    #[test]
    fn queued_work_is_reprioritized_when_focus_changes() {
        let order = Arc::new(Mutex::new(Vec::new()));
        let mut runtime = TerrainRuntime::new(
            RecordingGenerator {
                order: Arc::clone(&order),
            },
            TerrainRuntimeConfig {
                worker_count: 1,
                max_in_flight: 1,
                ..TerrainRuntimeConfig::default()
            },
        );
        runtime.set_desired([request(0, 1, 0), request(1, 1, 10), request(2, 1, 20)]);
        runtime.tick();
        runtime.set_desired([request(0, 1, 100), request(1, 1, 20), request(2, 1, 1)]);
        let ready = tick_until(&mut runtime, 3);
        acknowledge_ready(&mut runtime, &ready);
        assert_eq!(*order.lock().unwrap(), vec![0, 2, 1]);
    }
}
