[package]
name = "engine-script"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = []

[dependencies]
base64.workspace = true
engine-script-api = { path = "../engine-script-api" }
engine-serialize = { path = "../engine-serialize" }
libloading = "0.8"
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
