//! Vulkan backend.
//!
//! Gate 2 promotes this crate from a compile-only stub to a real
//! `ash`-based desktop renderer that opens a winit surface through the
//! `platform` crate, selects a physical device, builds a swapchain plus
//! frames-in-flight, and presents a triangle rendered from precompiled
//! SPIR-V shaders. The public RHI-v0 surface from `render-core` is
//! preserved unchanged; `VulkanRenderer` lives outside that contract by
//! design so RHI-v0 does not have to model the frame loop yet.

mod adapter;
mod device;
mod error;
mod frame;
mod instance;
mod pipeline;
mod renderer;
mod resource;
mod surface;
mod swapchain;

mod shaders_embedded {
    // Generated by `build.rs`. Exposes `TRIANGLE_VERT_SPV` and
    // `TEXTURED_*_SPV` constants as `&'static [u8]`. The constants are
    // empty when the artifacts haven't been produced yet; the renderer
    // surfaces `VulkanError::MissingShader` in that case.
    include!(concat!(env!("OUT_DIR"), "/shaders_embedded.rs"));
}

use render_core::{AdapterInfo, Backend, BackendKind, Device, DeviceDescriptor, RhiError};

pub use error::VulkanError;
pub use renderer::{VulkanRenderer, VulkanRendererDescriptor, VulkanSceneKind};

#[derive(Clone, Copy, Debug, Default)]
pub struct VulkanBackend;

impl VulkanBackend {
    pub const fn new() -> Self {
        Self
    }
}

impl Backend for VulkanBackend {
    fn kind(&self) -> BackendKind {
        BackendKind::Vulkan
    }

    fn enumerate_adapters(&self) -> Result<Vec<AdapterInfo>, RhiError> {
        // Adapter enumeration over RHI-v0 still requires a surface, which
        // is owned by [`VulkanRenderer`]. Gate 2 keeps the contract path
        // empty and surfaces real adapters through the renderer itself.
        Ok(Vec::new())
    }

    fn create_device(&self, _descriptor: &DeviceDescriptor) -> Result<Box<dyn Device>, RhiError> {
        // RHI-v0 has no frame/present API yet (see Gate 2 design notes);
        // the runtime path goes through `VulkanRenderer` for now.
        Err(RhiError::UnsupportedBackend)
    }
}

pub fn backend() -> VulkanBackend {
    VulkanBackend::new()
}
