use super::*;

// -------------------------------------------------------------------
// Component copy / paste model
// -------------------------------------------------------------------

const COMPONENT_CLIPBOARD_FORMAT_VERSION: u32 = 1;

/// A typed, serializable snapshot used by Copy/Paste Component Values.
///
/// [`ComponentRecord`] deliberately does not contain its registry key, so the
/// clipboard carries that key separately. This prevents a record copied from
/// one component type from being pasted over another component type merely
/// because both records happen to have compatible fields.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ComponentClipboard {
    format_version: u32,
    type_id: ComponentTypeId,
    component: ComponentRecord,
}

impl ComponentClipboard {
    /// Capture one component without mutating the scene.
    pub fn capture(
        scene: &Scene,
        entity_id: &PersistentId,
        component_type: &ComponentTypeId,
    ) -> Result<Self, EditorError> {
        let entity = scene
            .entities
            .iter()
            .find(|entity| &entity.persistent_id == entity_id)
            .ok_or_else(|| EditorError::EntityNotFound(entity_id.clone()))?;
        let component = entity
            .components
            .get(component_type)
            .cloned()
            .ok_or_else(|| EditorError::ComponentNotFound(component_type.clone()))?;
        Self::from_record(component_type.clone(), component)
    }

    /// Construct a typed clipboard from an already-owned record.
    pub fn from_record(
        type_id: ComponentTypeId,
        component: ComponentRecord,
    ) -> Result<Self, EditorError> {
        let clipboard = Self {
            format_version: COMPONENT_CLIPBOARD_FORMAT_VERSION,
            type_id,
            component,
        };
        clipboard.validate()?;
        Ok(clipboard)
    }

    pub fn type_id(&self) -> &ComponentTypeId {
        &self.type_id
    }

    pub fn component(&self) -> &ComponentRecord {
        &self.component
    }

    /// Serialize the validated clipboard as portable RON text.
    pub fn to_ron(&self) -> Result<String, EditorError> {
        self.validate()?;
        ron::ser::to_string_pretty(self, ron::ser::PrettyConfig::default())
            .map_err(|error| EditorError::ComponentClipboardSerialization(error.to_string()))
    }

    /// Parse and validate RON before any editor command can consume it.
    pub fn from_ron(serialized: &str) -> Result<Self, EditorError> {
        let clipboard: Self = ron::from_str(serialized)
            .map_err(|error| EditorError::ComponentClipboardSerialization(error.to_string()))?;
        clipboard.validate()?;
        Ok(clipboard)
    }

    pub fn validate(&self) -> Result<(), EditorError> {
        if self.format_version != COMPONENT_CLIPBOARD_FORMAT_VERSION {
            return Err(EditorError::InvalidComponentClipboard(format!(
                "unsupported format version {}",
                self.format_version
            )));
        }
        if self.type_id.trim().is_empty() || self.type_id.trim() != self.type_id {
            return Err(EditorError::InvalidComponentClipboard(
                "component type ID must be non-empty and contain no surrounding whitespace".into(),
            ));
        }
        if self
            .component
            .fields
            .keys()
            .any(|field| field.trim().is_empty())
        {
            return Err(EditorError::InvalidComponentClipboard(
                "component field names must be non-empty".into(),
            ));
        }
        Ok(())
    }
}

/// Atomically replace the serialized values of one existing component.
///
/// This command never removes or inserts a component key, so required
/// components remain present. [`prepare`](Self::prepare) is the entry point
/// for clipboard paste: it verifies that the clipboard and target have the
/// exact same type and captures a destination snapshot. Both execution and
/// undo reject stale scene state before making any mutation.
pub struct ReplaceComponent {
    entity_id: PersistentId,
    component_type: ComponentTypeId,
    expected: Option<ComponentRecord>,
    replacement: ComponentRecord,
    applied: bool,
}

impl ReplaceComponent {
    /// Create a deferred same-key replacement from a trusted record.
    ///
    /// This is useful for Reset Component values generated by the component
    /// catalog. Clipboard paste should use [`prepare`](Self::prepare), which
    /// additionally verifies the clipboard's type metadata.
    pub fn new(
        entity_id: PersistentId,
        component_type: ComponentTypeId,
        replacement: ComponentRecord,
    ) -> Self {
        Self {
            entity_id,
            component_type,
            expected: None,
            replacement,
            applied: false,
        }
    }

    /// Prepare a paste against an exact read-only snapshot of the target.
    pub fn prepare(
        scene: &Scene,
        entity_id: PersistentId,
        target_component_type: ComponentTypeId,
        clipboard: &ComponentClipboard,
    ) -> Result<Self, EditorError> {
        clipboard.validate()?;
        if clipboard.type_id != target_component_type {
            return Err(EditorError::InvalidComponentClipboard(format!(
                "cannot paste component type '{}' over '{}'",
                clipboard.type_id, target_component_type
            )));
        }
        let entity = scene
            .entities
            .iter()
            .find(|entity| entity.persistent_id == entity_id)
            .ok_or_else(|| EditorError::EntityNotFound(entity_id.clone()))?;
        let expected = entity
            .components
            .get(&target_component_type)
            .cloned()
            .ok_or_else(|| EditorError::ComponentNotFound(target_component_type.clone()))?;
        Ok(Self {
            entity_id,
            component_type: target_component_type,
            expected: Some(expected),
            replacement: clipboard.component.clone(),
            applied: false,
        })
    }

    pub fn replacement(&self) -> &ComponentRecord {
        &self.replacement
    }
}

impl Command for ReplaceComponent {
    fn name(&self) -> &str {
        "Replace Component Values"
    }

    fn execute(&mut self, scene: &mut Scene) -> Result<(), EditorError> {
        if self.applied {
            return Err(EditorError::InvalidComponentClipboard(
                "component replacement is already applied".into(),
            ));
        }
        let component = find_entity_mut(scene, &self.entity_id)?
            .components
            .get_mut(&self.component_type)
            .ok_or_else(|| EditorError::ComponentNotFound(self.component_type.clone()))?;
        if let Some(expected) = &self.expected {
            if component != expected {
                return Err(EditorError::InvalidComponentClipboard(format!(
                    "component '{}' changed after replacement was prepared",
                    self.component_type
                )));
            }
        } else {
            self.expected = Some(component.clone());
        }
        *component = self.replacement.clone();
        self.applied = true;
        Ok(())
    }

    fn undo(&mut self, scene: &mut Scene) -> Result<(), EditorError> {
        if !self.applied {
            return Err(EditorError::InvalidComponentClipboard(
                "component replacement was not executed".into(),
            ));
        }
        let expected = self.expected.as_ref().ok_or_else(|| {
            EditorError::InvalidComponentClipboard(
                "component replacement has no original snapshot".into(),
            )
        })?;
        let component = find_entity_mut(scene, &self.entity_id)?
            .components
            .get_mut(&self.component_type)
            .ok_or_else(|| EditorError::ComponentNotFound(self.component_type.clone()))?;
        if component != &self.replacement {
            return Err(EditorError::InvalidComponentClipboard(format!(
                "component '{}' changed before replacement undo",
                self.component_type
            )));
        }
        *component = expected.clone();
        self.applied = false;
        Ok(())
    }
}

// -------------------------------------------------------------------
// SetComponentField
// -------------------------------------------------------------------

pub struct SetComponentField {
    entity_id: PersistentId,
    component_type: ComponentTypeId,
    field_name: String,
    old_value: Option<Value>,
    new_value: Value,
}

impl SetComponentField {
    pub fn new(
        entity_id: PersistentId,
        component_type: ComponentTypeId,
        field_name: String,
        new_value: Value,
    ) -> Self {
        Self {
            entity_id,
            component_type,
            field_name,
            old_value: None,
            new_value,
        }
    }
}

impl Command for SetComponentField {
    fn name(&self) -> &str {
        "Set Component Field"
    }

    fn execute(&mut self, scene: &mut Scene) -> Result<(), EditorError> {
        let entity = find_entity_mut(scene, &self.entity_id)?;
        let comp = entity
            .components
            .get_mut(&self.component_type)
            .ok_or_else(|| EditorError::ComponentNotFound(self.component_type.clone()))?;
        let old_value = comp.fields.get(&self.field_name).cloned().ok_or_else(|| {
            EditorError::ComponentFieldNotFound {
                component_type: self.component_type.clone(),
                field_name: self.field_name.clone(),
            }
        })?;
        comp.fields
            .insert(self.field_name.clone(), self.new_value.clone());
        self.old_value = Some(old_value);
        Ok(())
    }

    fn undo(&mut self, scene: &mut Scene) -> Result<(), EditorError> {
        let entity = find_entity_mut(scene, &self.entity_id)?;
        let comp = entity
            .components
            .get_mut(&self.component_type)
            .ok_or_else(|| EditorError::ComponentNotFound(self.component_type.clone()))?;
        let old_value = self
            .old_value
            .take()
            .ok_or_else(|| EditorError::SceneCommandRejected {
                operation: "undo `Set Component Field`".to_string(),
                reason: "the command has no captured previous value".to_string(),
            })?;
        comp.fields.insert(self.field_name.clone(), old_value);
        Ok(())
    }
}

// -------------------------------------------------------------------
// AddComponent
// -------------------------------------------------------------------

pub struct AddComponent {
    entity_id: PersistentId,
    component_type: ComponentTypeId,
    component: ComponentRecord,
    activated_camera: bool,
}

impl AddComponent {
    pub fn new(
        entity_id: PersistentId,
        component_type: ComponentTypeId,
        component: ComponentRecord,
    ) -> Self {
        Self {
            entity_id,
            component_type,
            component,
            activated_camera: false,
        }
    }
}

impl Command for AddComponent {
    fn name(&self) -> &str {
        "Add Component"
    }

    fn execute(&mut self, scene: &mut Scene) -> Result<(), EditorError> {
        let entity = find_entity_mut(scene, &self.entity_id)?;
        if entity.components.contains_key(&self.component_type) {
            return Err(EditorError::ComponentAlreadyExists(
                self.component_type.clone(),
            ));
        }
        entity
            .components
            .insert(self.component_type.clone(), self.component.clone());
        self.activated_camera = false;
        if self.component_type == "engine.camera" && scene.scene_settings.active_camera.is_none() {
            scene.scene_settings.active_camera = Some(self.entity_id.clone());
            self.activated_camera = true;
        }
        Ok(())
    }

    fn undo(&mut self, scene: &mut Scene) -> Result<(), EditorError> {
        let entity = find_entity_mut(scene, &self.entity_id)?;
        entity.components.remove(&self.component_type);
        if self.activated_camera
            && scene.scene_settings.active_camera.as_deref() == Some(self.entity_id.as_str())
        {
            scene.scene_settings.active_camera = None;
        }
        Ok(())
    }
}

// -------------------------------------------------------------------
// RemoveComponent
// -------------------------------------------------------------------

pub struct RemoveComponent {
    entity_id: PersistentId,
    component_type: ComponentTypeId,
    was: Option<ComponentRecord>,
    was_active_camera: bool,
}

impl RemoveComponent {
    pub fn new(entity_id: PersistentId, component_type: ComponentTypeId) -> Self {
        Self {
            entity_id,
            component_type,
            was: None,
            was_active_camera: false,
        }
    }
}

impl Command for RemoveComponent {
    fn name(&self) -> &str {
        "Remove Component"
    }

    fn execute(&mut self, scene: &mut Scene) -> Result<(), EditorError> {
        let entity = find_entity_mut(scene, &self.entity_id)?;
        self.was = entity.components.remove(&self.component_type);
        if self.was.is_none() {
            return Err(EditorError::ComponentNotFound(self.component_type.clone()));
        }
        self.was_active_camera = self.component_type == "engine.camera"
            && scene.scene_settings.active_camera.as_deref() == Some(self.entity_id.as_str());
        if self.was_active_camera {
            scene.scene_settings.active_camera = None;
        }
        Ok(())
    }

    fn undo(&mut self, scene: &mut Scene) -> Result<(), EditorError> {
        if let Some(comp) = self.was.clone() {
            let entity = find_entity_mut(scene, &self.entity_id)?;
            entity.components.insert(self.component_type.clone(), comp);
        }
        if self.was_active_camera {
            scene.scene_settings.active_camera = Some(self.entity_id.clone());
        }
        Ok(())
    }
}
